- semcore/input-tags/src/InputTags.tsx
<InputTags.Value> can be omitted in some cases, for example when <InputTag> has maximum allowed number of tags.
This fixes an error occurring on focusing: TypeError: Cannot read properties of null (reading 'value')
reading from the ref moved into if statement
> Fix focusing when no input rendered

- semcore/textarea/CHANGELOG.md
- semcore/textarea/src/Textarea.jsx
Disabled rows recalculation on change event cause it may override rows recalculation on value prop change
@lsroman, is fix safe or it breaks some secret behaviour?
Source issue text:
> Если выставить min/max rows, чтобы автоматически считалась высота, то если у нас есть ограничение длинны инпута и при этом мы делаем copy/paste, то во время вставки высота textarea растянется по длинне вставляемой строки, но при этом вставки всего текста разумеется не будет.
> Это нужно как-то разрулить во время использования, или это что-то типо багули?
> Пример: https://codesandbox.io/s/lucid-leaf-pg8ply?file=/src/App.js
> Чтобы понять о чем речь, нужно вставить в инпут строчку 100+ символов
> Я догадываюсь что рассчет идет именно на ограничение MaxRows, но что делать когда нужно чтобы Textarea растянулся …
> [textarea] resize fix

- tools/babel-plugin-root/CHANGELOG.md
- tools/babel-plugin-root/babel-plugin-root.js
fixed syntax sugar of props passing. The sugar is about following transformation:
```diff
- const x = props;
+ const x = this ? this.asProps : arguments[0]
```
Transformation in root plugin passes props to `Root` node of component. 
What makes things worser, that transformation is wrong and currently works only because of components code second babel transformation, which has a undocumented behaviour, that sometimes [mess things up and confuses developers](https://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined-and-inserting-use-str).
That incorrect behaviour was detected during using esbuild to build components. We still can transform components thrice (build time in components repo, build with babel in host repo, build of the final bundle with …
> [babel-plugin-root] fixed syntax sugar of props passing

- semcore/scroll-area/CHANGELOG.md
- semcore/scroll-area/src/index.d.ts
> [scroll-area] make onScroll prop optional

- semcore/badge/CHANGELOG.md
- semcore/badge/__tests__/index.test.tsx
- semcore/badge/package.json
- semcore/badge/src/Badge.jsx
- semcore/utils/CHANGELOG.md
- semcore/utils/__tests__/index.test.tsx
- semcore/utils/src/reactToText.ts
- website/docs/components/badge/badge-a11y.md
- website/docs/components/badge/badge.md
- website/docs/components/badge/components/playground.jsx
- website/docs/components/badge/examples/base.jsx
- website/src/docs-components/PlaygroundGeneration.jsx
…onvert react component to text.
Signed-off-by: r.lysov <r.lysov@semrush.com>
Added support a11y for Badge component
- Add aria-hidden for component
- Added util function `reactToText` to convert react component to text
- Update documentation
The component becomes accessible 💪
Turn on the screen reader and listen to how it reads label text.
> [badge,utils] Add support a11y

- semcore/animation/CHANGELOG.md
- semcore/animation/src/Animation.jsx
- semcore/animation/src/Collapse.jsx
Currently `Collapse` component plays opening animation even if it was opened initially. Trying to fix it there.
@lsroman Is solution seems to be suitable for `Animation` components or may be more low-level sollution?
Reproducible example:
```
import React, { useState } from 'react';
import Accordion from '@semcore/accordion';
import { Text } from '@semcore/typography';
import { Flex, Box } from '@semcore/flex-box';
const Demo = () => {
const [v, setV] = useState(false);
return (
<div>
<div>
<button onClick={() => setV(!v)}>Toggle</button>
</div>
{v && (
<Accordion defaultValue={0}>
{[...new Array(3)].map((_, index) => (
<Accordion.Item value={index} key={index}>
<Accordion.Item.Toggle p="8px 12px" disabled={index === 2}>
<Flex alignItems="center">
<Accordion.Item.Chevron color="gray-300" …
```
> [animation] tried to fix init animation of opeend accordion

- semcore/button/CHANGELOG.md
- semcore/button/src/Button.jsx
- semcore/link/CHANGELOG.md
- semcore/link/src/Link.jsx
When passing a function or using components as a tag of other components, children are not detected correctly.
An example of incorrect work:
```
<FilterTrigger tag={Button}/ >
```
because in Button:
```
(Button)Children.origin === Children(FilterTrigger)
```
Right job 😇
Open example
> [button,link] Fixed aria warning detection.

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/RadialTree.tsx
- semcore/d3-chart/src/types/Area.d.ts
- semcore/d3-chart/src/types/Axis.d.ts
- semcore/d3-chart/src/types/Bar.d.ts
- semcore/d3-chart/src/types/Bubble.d.ts
- semcore/d3-chart/src/types/ClipPath.d.ts
- semcore/d3-chart/src/types/Donut.d.ts
- semcore/d3-chart/src/types/GroupBar.d.ts
- semcore/d3-chart/src/types/HorizontalBar.d.ts
- semcore/d3-chart/src/types/Hover.d.ts
- semcore/d3-chart/src/types/Line.d.ts
- semcore/d3-chart/src/types/Plot.d.ts
- semcore/d3-chart/src/types/ReferenceLine.d.ts
- semcore/d3-chart/src/types/ResponsiveContainer.d.ts
- semcore/d3-chart/src/types/ScatterPlot.d.ts
- semcore/d3-chart/src/types/StackBar.d.ts
- semcore/d3-chart/src/types/StackedArea.d.ts
- semcore/d3-chart/src/types/Tooltip.d.ts
- semcore/d3-chart/src/types/Venn.d.ts
I have replaced core typings of `CProps` (which represents replacement of children as render function) with locally introduced `MapsProps` (which represents mapper of the component props).  
Nothing changed in runtime. Types were just tuned to be compatible with runtime. You may ask how it was working before. The answer - it wasn't.
I have tried to use several `@semcore/d3-chart` examples from website. Seems like previously non-working examples now may be compiled successfully and nothing makes me suppose it may be broken.
Also I have ensured that no other component rather `@semcore/d3-chart` and `@secore/data-table` requires such typing.
> [d3-chart] fixed typings of `CProps`

- pnpm-lock.yaml
- semcore/time-picker/CHANGELOG.md
- semcore/time-picker/__tests__/time-picker.vo-test.ts
- semcore/time-picker/package.json
- semcore/time-picker/src/PickerFormat.jsx
- semcore/time-picker/src/PickerInput.jsx
- semcore/time-picker/src/TimePicker.jsx
- website/docs/components/time-picker/time-picker-a11y-report.md
- website/docs/components/time-picker/time-picker-a11y.md
Made time-picker accessible for Screen readers.
I have hid combobox popups for screen readers and added several necessary labels. Also I have removed weird searching for sibling inputs to focus it and replaced with predictable refs. 
I have added VO tests
> [time-picker] introduced a11y

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/index.d.ts
InputTrigger is declared as const, so we need to use `typeof`.
> [date-picker] fix InputTrigger subcomponent types

- semcore/illustration/CHANGELOG.md
- semcore/illustration/package.json
Added missing react-dom to peers deps. Same as #484.
Because @semcore/utils require to provide react-dom at dependent packages.
It works because of Node resolving algorithm. But if we use a more strict protocol (PNP) it will not work because there is no dependency hoisting.
This commit makes dependencies correct.
Not tested
> [illustration] added react-dom to peer deps

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
`DropdownMenu.Popper` closes when the `Enter` button is pressed.
for better a11y
by hands and keyboard
> [dropdown-menu] popper closes when enter button is pressed

- pnpm-lock.yaml
- semcore/i18n-unplugin/README.md
- website/docs/utils/i18n/examples/pagination-i18n.jsx
- website/docs/utils/i18n/i18n.md
- website/docs/utils/utils.md
I have added pages to tell users about how to deal with internationalization of our components. I have covered following topics:
1. `locale` and `i18n` props of components
2. `I18nProvider`
3. `i18n-unplugin` 
Previously we had no documentation about components internationalization. It became more important after introducing `i18n-inplugin` and covering more components with localization.
> [docs] added i18n page

- semcore/inline-input/src/InlineInput.tsx
- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
I have resoled the issue when plain tooltips were hijacking focus from inputs and so on.
Also I have replaced deprecated util function name.
Issue appeared after adding to all poppers `tabIndex={0}`. Our focus lock enabling algorithm started supposing that popper has some focusable content such inputs and icons while focusable was only popper by itself.
Other words, it turned out that `focus-lock` function `getFocusableIn` not only checks provided node children for focusability but also checks the node by itself.
I have updated algorithm to pass only popper children to `getFocusableIn` to resolve this issue.
Also, no `disableEnforceFocus` hack needed in `InlineInput` any more (I haven't updated inline-input changelog because change seems to be more internal and inline-input publish will …
> [popper] fixed focus hijacking by non editable poppers

- semcore/ellipsis/CHANGELOG.md
- semcore/ellipsis/src/Ellipsis.tsx
- semcore/ellipsis/src/index.d.ts
Now a defined list of props passed to ellipsis components are being passed to tooltip. A special prop `includeTooltipProps` allowes user to redefine a list of passed props. 
No ability to pass tooltip props seems weird and unexpected. I've made passing of props similar to feedback form component and redefining list of passed props as in checkbox component.
Manual testing was enough. The change is pretty easy.
> [ellipsis] supported passing tooltip props

- tools/babel-preset-ui/.babelrc.js
Fixing the problem of incorrect helper imports
Due to a bug in babel-runtime, not all helpers are imported correctly, instead, some of them are simply inlined INTO EVERY module, which affects code size and performance degradation
These are links to a detailed description of the problem
https://github.com/babel/babel/issues/10334
https://github.com/babel/babel/issues/10261
https://github.com/facebook/docusaurus/pull/2111
This fix will definitely improve code size and performance, but to make it even better, you need to get rid of **babel-runtime-helper** and use **@babel/preset-env** with properly configured **browserslist**, then native method will be used for the same code spread
All tests passed, build does not crash, website works locally
**Before:**
**After:**
> [global] fix transform-runtime helpers import

- semcore/table/CHANGELOG.md
- semcore/table/src/StickyHead.jsx
Use getBoundingClientRect().width instead of offsetWidth
getBoundingClientRect().width is a **float** while offsetWidth contains an **integer**
Сell borders in table body and header may not match, since the sizes in the header are calculated in the function using offsetWidth, and the table body itself is dynamic and can be a float
Previously it was imperceptible, there were no vertical borders in the design tables
Tested on my internal tables, also on local website and successful tests in ci
**Before:**
**After:**
> [table] fix colgroup calculation for StickyHead

- website/src/components/SearchHome.jsx
- website/src/utils/amplitude-client.js
- website/src/utils/cookie.ts
Added synonyms to site search in Algolia.
To have possibility to use synonyms in algolia we need the `userToken` parameter but we don't have users. For amplitude analytics we have the `deviceId` parameter (a randomly generated string that is stored in cookies). What happens if we use the `deviceId` parameter as the `userToken` parameter?
> [website] use amplitude device id as user token for algolia

- semcore/icon/CHANGELOG.md
- semcore/icon/__tests__/index.test.jsx
- semcore/icon/src/Icon.jsx
Removed automatic setting of `aria-hidden` to `true` because of some problems with a11y. If icon has `interactive` prop `aria-hidden` should be `false` (now it is always `true`).
> [icon] Removed automatic setting of aria-hidden to true

- semcore/utils/theme/tokens.json
Updated value for `chart-x-axis-accent-period-active` from `--gray-400` to `--gray-500` after recommendations from Level Access.
> [utils] update value for chart-x-axis-accent-period token

- pnpm-lock.yaml
- semcore/modal/CHANGELOG.md
- semcore/modal/package.json
- semcore/modal/src/Modal.jsx
- semcore/popper/CHANGELOG.md
- semcore/popper/package.json
- semcore/popper/src/Popper.jsx
- semcore/side-panel/CHANGELOG.md
- semcore/side-panel/package.json
- semcore/side-panel/src/SidePanel.jsx
- semcore/utils/CHANGELOG.md
- semcore/utils/package.json
- semcore/utils/src/use/useFocusLock.ts
I have removed `react-focus-lock` and build React integration on top of `focus-lock`. This integration doesn't create extra wrappers over element and both works perfectly with our popup components.
Our current focus lock mechanism a based on combination of react-focus-lock with some messy and non understandable by everyone in the team wrappers that work some-times. We got lot of reports about non working focus-lock and after animation update situation became even worse.  
Lot of manual testing for now.
> Perfect focus lock

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Radar.jsx
- semcore/d3-chart/src/a11y/insights.ts
- semcore/d3-chart/src/a11y/serialize.ts
I've improved Radar chart a11y by adding new data type for a11y module of d3-chart. It reuses existing translations and serialization.
Radar chart uses unusual format of data so existing a11y module while providing real summary of data wasn't helping users much. Adding new group much improved usefulness of generated summary.
> Radar chart a11y

- semcore/animation/CHANGELOG.md
- semcore/animation/src/Animation.jsx
- semcore/animation/src/index.d.ts
- semcore/animation/src/index.js
- semcore/dropdown-menu/src/DropdownMenu.jsx
- semcore/dropdown/src/Dropdown.jsx
- semcore/popper/src/Popper.jsx
- semcore/portal/CHANGELOG.md
- semcore/portal/src/Portal.tsx
- semcore/tooltip/src/Tooltip.jsx
- semcore/utils/CHANGELOG.md
- semcore/utils/src/enhances/contextEnhance.tsx
I have added prop `ignorePortalsStacking` for portals.
After animation update we faced following issue with tooltips in modals when tooltip is applied to elements which width is close to the width of the modal.
Going deeper showed that the reason is nested portals:  modal is rendered in portal, but creates portal provider inside of that. It ensured z-index are correct and position of inner poppers is related to position of modal (what is very important in animations!) on other hand in such situation popperjs modifier `computeStyles` finds parent node with scrolling and tries to place popper inside of that scrollable parent.
Such behavior is very good for most cases except cases when tooltip trigger size is almost equal to the size of scrollable parent, where popper is going to be placed. …
> [global] supported ignoring parent portals nesting

- website/docs/components/dropdown-menu/dropdown-menu.md
Fix an out of place round bracket in the DropdownMenu documentation.
> [docs] fix typo in the dropdown-menu doc

- semcore/data-table/src/Body.tsx
Added a key to the **SGroupCell** component
When you use **ROW_GROUP** to merge cells, you get a missing key error
Checked on the local version of the website
> [data-table] added key on groupCell

- semcore/animation/CHANGELOG.md
- semcore/animation/src/Collapse.jsx
- semcore/animation/src/style/animate.shadow.css
- semcore/animation/src/style/keyframes.shadow.css
I have rebuild collapse animation from css `animation` to css `transition`.
Currently collapse animation works fine except working in Safari.
I have manually tested it in Safari, Chrome and Firefox. Seems to work fine in all modern browsers.
> [animation] fixed collapse animations in Safari

- semcore/utils/CHANGELOG.md
- semcore/utils/src/enhances/keyboardFocusEnhance.tsx
Currently it's impossible to make autofocus that highlights element with the focus ring. If it's made via `useEffect`, no ring is visible because keyboardFocusEnhance in 99% cases consider it as non keyboard triggered.
Manual testing.
> [utils] all focusable components get `autoFocus` prop via `keyboardFocusEnhance`

- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
- semcore/popper/src/style/popper.shadow.css
- semcore/utils/src/use/useFocusLock.ts
- website/docs/style/design-tokens/components/design-tokens.json
Our poppers are focusable but default focus outline is hidden. It's ok for mouse users but not so well for keyboards users. I have added keyboard focus highlight to improve their UX.
Only manually.
> added popper keyboard focus highlight

- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
Now updating `strategy`, `modifiers`, `placement`, `offset`, `pr…eventOverflow`, `arrow`, `flip`, `computeStyles`, `eventListeners` or `onFirstUpdate` props now triggers popper positioning update
Previously updating main props of popper component were not triggering popper instance update. Now it's do.
Only manual testing.
Before:
https://github.com/semrush/intergalactic/assets/31261408/4d4ab3f4-5b73-40eb-9cf8-a5d6e24fac97
After:
https://github.com/semrush/intergalactic/assets/31261408/ab68addc-30cd-46d6-84f0-c590412e50bd
> popper repositioning

- semcore/select/CHANGELOG.md
- semcore/select/src/InputSearch.jsx
If `Select` gets explicit `undefined` it overrides default `m` value. In combination with `InputSearch` it breaks rendering.
As far `| undefined` is union of all optional types in Typescript, out component should at least do not break rendering  
Manual testing.
> [select] `InputSearch` default `size`

- semcore/textarea/CHANGELOG.md
- semcore/textarea/src/Textarea.jsx
- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
- tools/continuous-delivery/src/fetchFromNpm.ts
We had edge case that textarea component wasn't resizing if `minRows` prop provided without `maxRows`.
I have added much more complex condition that now handles resizing well even in the case above..
Only manual testing.
> [textarea] `minRows` now works without `maxRows`

- semcore/button/src/Button.jsx
- semcore/core/CHANGELOG.md
- semcore/core/src/enhancement/Root.tsx
- semcore/flex-box/CHANGELOG.md
- semcore/flex-box/src/Box/useBox.tsx
- semcore/flex-box/src/Flex/useFlex.tsx
- semcore/icon/src/Icon.jsx
- semcore/link/src/Link.jsx
Sometimes it might very helpful to pass React.Fragment as a component tag. Sure, it will disable most of components functionality but it seems to a an important escape hatch. Currently it works but with React warnings (e.g. "Invalid prop `className` supplied to `React.Fragment`").
All existing tests should pass well.
> [global] supported `tag={React.Fragment}`

- semcore/format-text/CHANGELOG.md
- semcore/format-text/src/style/format-text.shadow.css
- semcore/icon/CHANGELOG.md
- semcore/typography/CHANGELOG.md
- semcore/typography/src/index.d.ts
- semcore/typography/src/style/text.shadow.css
- website/docs/style/typography/examples/format-text.tsx
- website/docs/style/typography/examples/text-emphasis.tsx
We have a request for providing default styles for font with `monospace` font-family and `code` tag. So I've added `monospace` prop for Text component and styles for `code` tag for FormatText component. 
**I need you to check these updates from the frontend side.**
I used our playground and examples on the website to test if the new property and `code` tag was added and can be used for Text and FormatText components.
> Feature/add monospace style for Text and FormatText

- semcore/utils/CHANGELOG.md
- semcore/utils/src/use/useFocusLock.ts
`useFocusLock` hook is merging if multiple versions of it is loaded on one page.
It's critical to provide smooth UX and prevent focus lock wars.
To make it work on page where multiple projects use multiple versions of React, the React isolation was added. However, it was added with a mistake – nested hooks wasn't isolating React.
This PR adds such isolation.
It was tested manually and I am going to test prerelease version on real world project before publishing release.
> [utils] React invalid Hooks call caused by `useFocusLock` in some rare cases from it's nested hooks

- semcore/base-trigger/CHANGELOG.md
- semcore/base-trigger/src/FilterTrigger.jsx
- semcore/utils/CHANGELOG.md
- semcore/utils/src/assignProps.ts
Initially filter trigger had `button` role. Then we found that it's wrong when container has role `button` while having buttons (clear buttons) inside. So we changed it to `group`. 
But action it's not so good. We always needed `button` role when filter empty has empty state and `group` when it has clear button inside. It wasn't implemented yet because props overriding hack (prefixing with `use:`) was working only with style props. Now I made it to work with any prop and made FilterTrigger role group work as needed.  
All tests are passing. Manual tests confirmed that FilterTrigger role is changing
> [base-trigger] empty FilterTrigger now gets role `button` during empty state instead of `group`

- semcore/base-trigger/CHANGELOG.md
- semcore/base-trigger/src/BaseTrigger.jsx
- semcore/base-trigger/src/style/base-trigger.shadow.css
- semcore/utils/CHANGELOG.md
- semcore/utils/__tests__/index.test.tsx
- semcore/utils/src/assignProps.ts
- semcore/utils/src/ref.ts
I found several issues.
1. BaseTrigger generates warnings about using non existing attribute. That would be better fixed after https://github.com/semrush/intergalactic/issues/748 but for now I just used the attribute name that is not passing _the grand regexp_.
2. If function is provided to ref prop, it will be called twice in deep nested components because assignProps were not clearing forwardRef prop after merging it into ref prop.
3. ScrollArea component remounts after first render. It caused by assignProp function that generates new ref function callback on every render. It cannot be fixed with current core and is not fixed in this PR.
All existing tests should pass.
> Small core fixes

- semcore/popper/CHANGELOG.md
- semcore/popper/__tests__/index.test.jsx
- semcore/popper/src/Popper.jsx
disable scrolling to a Select component when Select.Menu is opened and I click outside of the menu
I have added unit tests, and I have tested it manually on playground
> [popper] Prevent to return focus to `Trigger` after popper is closed

- semcore/notice-bubble/CHANGELOG.md
- semcore/notice-bubble/__tests__/index.test.tsx
- semcore/notice-bubble/src/style/notice-bubble.shadow.css
- website/docs/components/notice-bubble/examples/not-in-portal.tsx
- website/docs/components/notice-bubble/notice-bubble-example.md
Fixed view NoticeBubble in Container without portal
I have tested it manually, added example in the documents and fixed unit tests for new behavior
> [notice-bubble] added sticky position for non portal NoticeBubble's

- semcore/utils/CHANGELOG.md
- semcore/utils/src/use/useFocusLock.ts
When updating focus lock from version 2 to version 3 `useUniqueId` hook was removed.
Due to replacing useFocusLock hook in runtime, the order of hooks must be preserved.
So, useUniqueIdHookMock helps to preserve hooks order when hook is being replaced from version 2 to version 3.
It was tested on stage that uses multiple versions of `@semcore/ui` and where both focus lock v2 and focus lock v3 are present.
> [utils] fixed focus lock merging was causing invalid hooks order error

- semcore/side-panel/CHANGELOG.md
- semcore/side-panel/__tests__/index.test.jsx
- semcore/side-panel/src/SidePanel.jsx
In Api for SidePanel we have `PortalProps`, but in fact, we supported only `disablePortal`. I have added `ignorePortalsStacking` too.
I have added unit tests
> [side-panel] added passing ignorePortalsStacking prop to the Portal

- semcore/utils/CHANGELOG.md
- semcore/utils/src/enhances/animatedSizeEnhance.tsx
- website/docs/components/select/examples/custom-trigger.tsx
> [base-trigger] Do not animate the width/height of a node if they are specified as a percentage

- semcore/utils/CHANGELOG.md
- semcore/utils/src/use/useColorResolver.ts
- website/docs2/data-display/color-palette/color-palette.md
- website/src/docs-components/Color.jsx
The color resolver contained a very stupid mistake that was making using old color palette impossible. It has been existing in our codebase for about two weeks and it's insane that we haven't spotted it.
Basically it was removing `--` prefix from variable name and then was checking does this variable exist in map where all names had prefix `--`. So our potential users had to use `----{variable_name}` syntax if they were trying to overcome the issue.
The fix is clear.
> [utils, website] fixed old palette resolving and also fixed palette view on website

- semcore/scroll-area/CHANGELOG.md
- semcore/scroll-area/src/style/scroll-area.shadow.css
https://github.com/semrush/intergalactic/issues/867
It's not general solution but should fix most cases as far normally focus ring should overlap even z-indexed elements. 
Only manual tests.
Before:
After:
> [scroll-area] fixed that sometimes scroll area focus ring was overlapped by sibling elements

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Body.tsx
axe-core (used by Lighthouse for a11y audits) rises warning if table (or anything with role='table') contains any non-table elements. It was also related to scrollbars inside of tables. 
Solution is ugly a little bit but should not break anything.
Manually with lighthouse.
> [data-table] fixed lighthouse accessibility warning about existing scrollbar role element inside of the table

- pnpm-lock.yaml
- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/components/InputTrigger.jsx
Date pickers accept `value` as Date, string or number. It wasn't working in input triggers (while displaying normally) inside of date picker calendar. I have added simple mapping inside of input trigger.
I have tested it manually.
> [date-picker] fixed input trigger were not displaying date or date range when it is passed as number or string

- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/Tooltip.jsx
#942 
I have tested it manually
> [popper, tooltip] fixed incorrect behavior in Tooltip when it has a focusable elements inside themself and don't close from the first esc keypress

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/component/ChartLegend/LegendItem/legend-item.shadow.css
Found that ellipsis doesn't work in the chart legend table grid.
I have found some wierd hacks ([1](https://css-tricks.com/preventing-a-grid-blowout/), [2](https://stackoverflow.com/questions/36230944/prevent-flex-items-from-overflowing-a-container)) that make everything work like a charm.
It almost impossible to test in our screenshot unit tests because ellipsis needs a trimming rerender.
Before:
After:
> [d3-chart] fixed chart legend table trimming with Ellipsis component

- semcore/d3-chart/CHANGELOG.md
- semcore/input-mask/CHANGELOG.md
- semcore/input-mask/__tests__/index.test.tsx
- semcore/input-mask/src/InputMask.tsx
It was found that if initial value is not allowed by outer pipe function, component blows up due to error inside of `input-mask-core`. Input mask core have no updated last 5 years and migrating to some other library is very painful (but needed in the future).
Here is an example when it was initially found – selected day is disabled https://codesandbox.io/p/sandbox/frosty-cloud-25yvw7?file=%2Fsrc%2FApp.tsx
Also you can checkout added test to for more simple example.
Test that was added wasn't initially was throwing error like 'unable to read xxx.length of undefined` from somewhere of compressed `text-mask-core`.
After change it passed well. DatePicker example from above also works fine after the fix.
> [input-mask] fixed that component was breaking a page when initial value was not allowed by outer pipe

- website/docs/table-group/data-table/data-table-code.md
Resolved #978 
Since we've added `overflow: auto` for the `playground-runtime` containers, `top` property with `position: sticky` works incorrect. So, I removed `top` property in examples and added comment there.
> [website] fixed 'Fixed header' example in data-table

- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
- semcore/utils/CHANGELOG.md
- semcore/utils/src/enhances/keyboardFocusEnhance.tsx
Currently when focus on page is on the popper trigger focus catcher, the focus ring is not visible. 
I have added context that enabled components that use keyboardFocusEnhance inside of popper trigger to highlight when  some of trigger focus catchers are focused by keyboard interaction.
Not sure how to add tests for that, ideas are welcome.
> [popper] added visual focus ring on trigger when focus is got by focus catcher

- website/docs/.vitepress/renderSandbox.ts
- website/docs/.vitepress/theme/Sandbox.vue
- website/docs/.vitepress/theme/isolateStyles.ts
- website/docs/.vitepress/theme/style.css
- website/src/components/playground/Playground.jsx
Time to time website styles break code examples. I have put every code example inside of shadow root to isolate them.
To test that isolation works I have added `* { color: red !important; }` to `website/docs/.vitepress/theme/style.css`. It changed color of both examples and everything else before change. After making change examples were the only things that wasn't red.
To test that nothing else broken I've just navigated over few pages – seems that nothing were broken.
> [website] isolated examples styles from website styles in shadow roots

- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
We have focus catch element that catches focus after closing popper. It's placed right next to the trigger and works like a charm for for `interaction=hover` и `interaction=focus` but extremely weird for `interaction=click`. 
After returning focus it looks like trigger is focused but keyboard pressing doesn't work. 
Also I found issue with `triggerRef` – instead of `useRef` it was using `createRef` that has no sense in functional components.
Manual testing showed that everything works good.
> [popper] fixed that after closing popper with interaction `click` focus is returned to the trigger instead of special focus catch element

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
When popper is closed and not mounted, the updated code was trying to focus it. I have added optional chaining to fix it.
No new tests needed. In manual testing the error is gone.
> [dropdown-menu] fixed pressing `ArrowUp`/`ArrowDown` on closed  trigger was causing error in console

- .github/workflows/publish-unlocked-release.yml
- tools/continuous-delivery/src/intg-release/publishPreRelease.ts
- tools/continuous-delivery/src/intg-release/publishRelease.ts
- tools/continuous-delivery/src/intg-release/publishTarball.ts
We need to have a history of commits, for find correct one for publish, so, I've added `fetch-depth` to `checkout` step.
And I've fixed publish prereleases with `beta` tag.
> [global] New release

- semcore/icon/CHANGELOG.md
- tools/icon-transform-svg/__tests__/__fixtures__/color/circle/m/index.d.ts
- tools/icon-transform-svg/__tests__/__fixtures__/color/circleNew/m/index.d.ts
- tools/icon-transform-svg/__tests__/__fixtures__/external/mixNewl/index.d.ts
- tools/icon-transform-svg/__tests__/__fixtures__/external/mixl/index.d.ts
- tools/icon-transform-svg/__tests__/__fixtures__/path/m/index.d.ts
- tools/icon-transform-svg/__tests__/__fixtures__/pathNew/m/index.d.ts
- tools/icon-transform-svg/__tests__/__fixtures__/pay/polygon/index.d.ts
- tools/icon-transform-svg/__tests__/__fixtures__/pay/polygonNew/l/index.d.ts
- tools/icon-transform-svg/config.js
- website/docs/components/accordion/accordion-api.md
- website/docs/components/modal/modal-api.md
Icons typings are controlled by `icon-transform-svg` component. So during major typings update it was forgot to be updated. It's why `IIconProps` was used in component typings instead of `IconProps`.
Also I have updated all use of `I*Props` in docs
All existing tests should pass
> [icon] fixed typings

- semcore/input-tags/CHANGELOG.md
- semcore/input-tags/src/InputTags.tsx
Long time ago we have added  `role=list` and `role=listitem`  to input tags container and tags. 
It doesn't improve component a11y (VO doesn't describe it as list) and created new a11y issues because forced us to handle edge cases such inputs that are restricted in lists.
I have tested it with Voice over in Safari. It's output became more informative (reading count of tags after reading first tag content).
> [input-tags] removed `role=list` and `role=listitem` from tags container and tags as it was misleading screen readers and other assistive technologies

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/__tests__/index.test.tsx
- semcore/d3-chart/src/a11y/focus.ts
current realisation of method doesn't try to find focusable elements in children recursively, I've fixed it.
> [d3-chart] fixed method for find next focusable element

- semcore/outside-click/CHANGELOG.md
- semcore/outside-click/src/OutsideClick.tsx
- semcore/utils/CHANGELOG.md
- semcore/utils/src/getEventTarget.ts
- website/docs/utils/popper/popper.md
We recently moved all website examples into Shadow DON while all components was never tested to work in Shadow DOM. It was found that https://developer.semrush.com/intergalactic/utils/popper/popper render function examples closes immediately after opening. 
The example was broken because OutsideClick tries to get what element is clicked and in case of using shadow dom elements it's the shadow dom container – the whole playground. So, for outside click component every click was the outside one.
The change is extremely simple – I've just made it to support shadow DOM with full backward capability. 
So I think we do not need shadow DOM tests for now.
> [outside-click, utils] fixed outside clicks handling in shadow dom

- semcore/base-trigger/CHANGELOG.md
- semcore/base-trigger/src/FilterTrigger.jsx
- semcore/base-trigger/src/index.d.ts
- website/docs/components/filter-trigger/examples/programmatic_focus.tsx
- website/docs/components/filter-trigger/filter-trigger-a11y.md
- website/docs/components/filter-trigger/filter-trigger-code.md
This PR fixes two issues:
1. FilterTrigger uses div with role="button" instead of just button. It's why label with htmlFor doesn't work for FilterTrigger.
2. FilterTrigger sets ref to it's wrapper. So developers can't set focus on focus trigger programmatically. I've added `triggerRef` prop and example how to use it.
Manual testing on website examples.
> [86bxczer3][base-trigger] added filter trigger triggerRef prop and corresponding docs

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Dots.jsx
During the chart patterns update I've accidentally removed `value` prop from d3 dots components. This PR adds it back.
-
> [86bxfdpxp][d3-chart] dots was missing value prop in props mapping function

- semcore/carousel/CHANGELOG.md
- semcore/carousel/src/Carousel.tsx
- semcore/color-picker/CHANGELOG.md
- semcore/color-picker/__tests__/index.test.tsx
- semcore/color-picker/src/ColorPicker.tsx
- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/a11y/PlotA11yView.tsx
- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Head.tsx
- semcore/icon/CHANGELOG.md
- semcore/icon/src/Icon.jsx
- semcore/inline-edit/CHANGELOG.md
- semcore/inline-edit/src/InlineEdit.tsx
- semcore/inline-input/CHANGELOG.md
- semcore/inline-input/src/InlineInput.tsx
- semcore/input-tags/CHANGELOG.md
- semcore/input-tags/src/InputTags.tsx
- semcore/pills/CHANGELOG.md
- semcore/pills/src/Pills.jsx
- semcore/switch/CHANGELOG.md
- semcore/switch/__tests__/index.test.tsx
- semcore/switch/src/Switch.jsx
- semcore/tab-panel/CHANGELOG.md
- semcore/tab-panel/src/TabPanel.jsx
- semcore/tag/CHANGELOG.md
- semcore/tag/__tests__/index.test.tsx
- semcore/tag/src/Tag.jsx
- semcore/wizard/CHANGELOG.md
- semcore/wizard/__tests__/index.test.tsx
- semcore/wizard/src/Wizard.jsx
We have a lot of interactive elements that listen to Enter keydown and call the click handlers. It's also expected for them to react on Space keydowns. 
I've checked out all placed in code where keydown
I've manually tested every updated component. Nothing seems to be risky or require additional unit tests (over existing ones for Enter key).
> [86bxd8qjz] added space keydown handler alongside all enter keydown handlers

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/types/Area.d.ts
- semcore/d3-chart/src/types/Bar.d.ts
- semcore/d3-chart/src/types/Bubble.d.ts
- semcore/d3-chart/src/types/Donut.d.ts
- semcore/d3-chart/src/types/GroupBar.d.ts
- semcore/d3-chart/src/types/HorizontalBar.d.ts
- semcore/d3-chart/src/types/Line.d.ts
- semcore/d3-chart/src/types/Plot.d.ts
- semcore/d3-chart/src/types/Radar.d.ts
- semcore/d3-chart/src/types/ScatterPlot.d.ts
- semcore/d3-chart/src/types/StackBar.d.ts
- semcore/d3-chart/src/types/StackedArea.d.ts
- semcore/d3-chart/src/types/Venn.d.ts
- website/docs/core-principles/writing-code/examples/making-wrappers.tsx
- website/docs/data-display/d3-chart/d3-chart-code.md
- website/docs/data-display/d3-chart/examples/axes-titles.tsx
- website/docs/data-display/d3-chart/examples/custom-patterns.tsx
- website/docs/data-display/d3-chart/examples/export-to-image.tsx
- website/docs/data-display/d3-chart/examples/low-level-components-use.tsx
- website/docs/patterns/informer/examples/basic-usage.tsx
- website/docs/style/typography/examples/formattext-nested-lists.tsx
After enabling type checking for many docs examples many type issues was found. I've fixed many of them in docs. Also I found that forgot to add `patterns` prop type to many charts – it's not critical cause developers can set `patterns` on `Plot`, but prop also should exist on chart components itself.
By ts type checking
> [d3-chart, docs] fixed types

- semcore/base-trigger/CHANGELOG.md
- semcore/base-trigger/src/FilterTrigger.jsx
When `button` tags was added to FilterTrigger, `type="button"` was forgotten to be added. So, in forms FilterTriggers was always considered (by browsers) as submit buttons. It was causing them to open on form submit instead of real form submitting.
Too stupid fix. Manual testing was enough.
> [86bxht8wd][base-trigger] fixed pressing enter in forms was triggering `FilterTrigger` to open

- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
- website/docs/components/tooltip/examples/singleton.tsx
- website/docs/components/tooltip/tooltip-code.md
Our tooltip singleton example was almost useless because it contained same tooltip content for every option.
I have update example to deal with it.
Also I found a bug in hour popper prevents infinite popper reopens on trigger focus.
Also I made singleton example weird a bit  after finding out that added state rerenders whole example with select and makes all example unusable.
Manual testing only.
> [86bxce63v][popper, tooltip] improved tooltip singleton example

- pnpm-lock.yaml
- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/__tests__/index.test.tsx
- semcore/dropdown-menu/package.json
- semcore/dropdown-menu/src/DropdownMenu.jsx
- semcore/dropdown-menu/src/index.d.ts
- semcore/dropdown-menu/src/style/dropdown-menu.shadow.css
- website/docs/components/dropdown-menu/examples/nested.tsx
Our dropdown menus are not accessible in case of building nested menus. Making #1102 unlocked the path to make it accessible. This PR adds special `DropdownMenu.Nesting` and `DropdownMenu.Nesting.Trigger` components that allows to build accessible nested menus.
I have added new unit tests that cover testable cases.
> [86bxfdn8a] Dropdown menus nesting

- pnpm-lock.yaml
- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/__tests__/index.test.tsx
- semcore/dropdown-menu/package.json
- semcore/dropdown-menu/src/DropdownMenu.jsx
- semcore/dropdown-menu/src/index.d.ts
- semcore/dropdown-menu/src/style/dropdown-menu.shadow.css
- semcore/utils/src/use/useFocusLock.ts
- website/docs/components/dropdown-menu/examples/nested.tsx
This PR is based on #1100 and provides alternative approach to fix dropdown menu a11y.
Key differences:
1. Changes in this PR doesn't include moving `aria-activedescendant` from trigger to popper as it breaks combobox pattern support.
2. Changes in this PR includes little fixes in focus lock that crucial for correct focus lock in Dropdown Menu items.
3. Instead of creating an independent focus management system, a common focus lock is used.
4. PR also includes fixes applied to keydowns handling that are important for nested dropdowns.
Unit tests & manual testing. Also I was testing it with nested dropdowns.
> [86bx4vya5] alternative dropdown-menu a11y improvemnt 

- semcore/select/CHANGELOG.md
- semcore/select/src/Select.jsx
It was misleading assistive technologies and creating a "screen reader focus ring shift" effect, `aria-controls` is kept on the `Select.Trigger`.
See screenshots.
Not sure it's possible to test. And that tests are needed.
Before:
After:
> [select] removed `aria-owns` from the `Select.Trigger`

- semcore/base-trigger/CHANGELOG.md
- semcore/base-trigger/src/FilterTrigger.jsx
Our Filter trigger was found to not be accessible cause it was setting aria attributes on outer wrapper instead of inner trigger. I've fixed it. Solution is not perfect cause we need to add deep component customization but it's good enough just to make it accessible.
Manual testing, soon I will enable a11y tests.
> [86bxkev49][base-trigger] fixed that filter trigger was setting aria attributes to wrapper instead of inner trigger

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Body.tsx
Right now, we setup row size observer in first render and if haven't have first row yet, don't try to setup it again. I've changed this logic, to setup row size in requestAnimationFrame - guaranty that we painted first row 
> [86bxke46b][data-table] fixed virtual scroll in table

- website/docs/components/input-tags/examples/entering_and_editing_tags.tsx
I've just fixed example for `InputTags` - we need as we've added `preventDefault` in some places, so, previous condition was always false.
> [86bxkecx4][website] fixed input tags example

- semcore/time-picker/CHANGELOG.md
- semcore/time-picker/src/PickerInput.jsx
`input` tags in time picker are very narrow. It's narrow because it needs background highlight when focused. This background highlight cannot be made by `:after` or `:before` pseudo elements because `input` tag cannot contain it. 
While Select trigger is more narrow than popper, it's displayed incorrectly. To overcome it, I've added default `offset` prop that compensate it on popper.
Our screenshot tests can't screenshot popper in right position, so only manually.
Before:
After:
> [86bxfj0xv][time-picker] fixed horizontal offset

- semcore/button/CHANGELOG.md
- semcore/button/src/style/button.shadow.css
For unknown reason postcss with `@semcore/babel-plugin-react-semcore` break on `SButton+&` selector. I've replaced this selector with a simpler equivalent that doesn't break. 
Manually on existing project only.
> [86bxp9vbw][button] fixed old themization

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/__tests__/index.test.tsx
- semcore/dropdown-menu/src/DropdownMenu.jsx
After #1111 it was found that focusable elements inside of dropdown-menu footer are not very accessible. It's very hard to get to them with tab key navigation.
I have added additional check that disabled focus lock if focus goes out of item but is kept inside of dropdown popper.
Manually on wide range of cases and with unit test on the main case – tab navigation goes from one focusable to another.
> [dropdown-menu] footer focus a11y

- semcore/tag/CHANGELOG.md
- semcore/tag/src/style/tag.shadow.css
For now, `:before` container in `Tag` overlaps all tag content, so, `onClick` for `Tag.Close` doesn't fire. I've fixed it.
I've tested it manually.
> [tag] fixed order in layers for close icon

- semcore/data-table/CHANGELOG.md
- semcore/table/src/StickyHead.jsx
- semcore/table/src/index.d.ts
- semcore/table/src/style/table.shadow.css
It's like https://github.com/semrush/intergalactic/pull/1132 but without breaking changes.
Manually only.
> [86bxngmv2][table] allowed to disable StickyHead portal

- semcore/carousel/CHANGELOG.md
- semcore/carousel/__tests__/index.test.tsx
- semcore/carousel/src/Carousel.tsx
Before fix, `onIndexChange` return absolute select index(negative value or more then items count). I've added function to get correct value (between 0 and max count of items).
I've fixed unit tests for this new behaviour
> [86bxpbc49][carousel] fixed onIndexChange to return correct value

- semcore/animation/CHANGELOG.md
- semcore/animation/src/Collapse.jsx
- semcore/animation/src/index.d.ts
- semcore/animation/src/style/keyframes.shadow.css
Collapse element is used for nested data tables. All browsers have a weird behavior that `position: sticky` doesn't work if any of parents has `overflow: hidden` (or `overflow-y: hidden`  or `overflow-x: hidden` , it doesn't matter).
https://stackoverflow.com/questions/47095596/body-overflow-x-hidden-breaks-position-sticky
The best option I found to resolve the issue and keep everything work was to replace `overflow: hidden` with `overflow: clip` and add `display: flow-root;`.
I've failed to add corresponding tests. So, manual testing only.
Before:
After:
> [86bxq19r9][animation] collapse replaced overflow hidden with overflow clip

- website/docs/table-group/table-showcase/table-showcase.md
No dev review needed. Just a small typo fix for URL of the accordion case for Table.
> [website] fix URL typo for accordion case in Table docs

- semcore/base-trigger/CHANGELOG.md
- semcore/base-trigger/src/FilterTrigger.jsx
On one of product that uses our lib it was found that FilterTrigger shares `triggerRef` from defaultProps across instances. It seems that it's because defaultProps param is static but I can't reproduce it in our playgrounds or tests env.
Only on the product. After the change the bug gone.
> [86bxry0ne][base-trigger] fixed that filter trigger was sharing triggerRef between instances

- semcore/animation/CHANGELOG.md
- semcore/animation/src/Collapse.jsx
It was found that with `preserveNode` collapse animation wasn't working properly – after finishing animation the collapse component was always showing it's cotnent.
We have no autotests for animations 🤷
> [86bxthz5q][animation] fixed collapse animation with preserveNode prop

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Bar.jsx
- website/docs/data-display/bar-chart/examples/date-format.tsx
For the Bar charts with more then 5 columns we created empty summary, because we don't define X and Y axis values in Bar component. I've fixed it.
Manually
> [86bxtdz6n][d3-chart] added logic to define X and Y axis for a11y summary in Bar charts

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/components/DateRangeComparatorAbstract.jsx
- semcore/date-picker/src/components/RangePickerAbstract.jsx
It was found that in month range pickers the second calendar wasn't usable from keyboard. I found that the function setNextDisplayedPeriod was made very weird and unpredictable. I refactored it – now it's much simpler and predictable.
Manually on all types of date pickers.
> [86bxfdxh2][date-picker] refactored range pickers setNextDisplayedPeriod and fixed it's wrong dates results in month pickers

- .github/workflows/publish-prerelease.yml
- tools/continuous-delivery/bin/intg-publish-prerelease.ts
- tools/continuous-delivery/index.ts
- tools/continuous-delivery/package.json
- tools/continuous-delivery/src/intg-release/closeTasks.ts
- tools/continuous-delivery/src/intg-release/updateIntergalacticChangelog.ts
- tools/continuous-delivery/src/utils/gitUtils.ts
`simple-git` `tags` command return list of tags, sorted by semantic version number by default. So, as currentTag in release we have latest prerelease tag of this version. Also, sort by `creatordate` doesn't work, because for prerelease and release we'll have the same dates, so, we'll get prerelease too.
I've changed `getCurrentTag` method to use `git describe` and fixed version in message to slack and fixed a list of tasks to close.
Also, I've changed logic of generating changelogs and publishing for `intergalactic` package.
> [global] some fixes in publish release scripts

- semcore/utils/CHANGELOG.md
- semcore/utils/src/uniqueID.ts
On one of existing project hydration errors were faced. It was caused by different `uid` generated by `useUID` hook on the client and on the server. I made it to use React.useId when it's available (we want to support older versions of React).
I've modified code of library in node_modules of that project and ensured that hydration errors have gone.
> [86bxwjwjc][utils] use React.useId in useUID when it's avaialble

- semcore/inline-input/__tests__/index.test.tsx
- semcore/inline-input/src/index.d.ts
Currently it's not possible to disable onBlurBehavior. This PR adds such option.
Manually and with a new unit test case.
> [86bxyarnp][inline-input] added onBlurBehavior=none

- semcore/input-tags/CHANGELOG.md
- semcore/input-tags/src/InputTags.tsx
Backward navigation on page with `shift+tab` makes user stuck in container if it's empty. It happens because focused input tags container moves focus to the input in the end of container. I've added additional check to prevent looping focus back to this input.
Only manually.
> [86bxyc2u2][input-tags] wasn't allowing to move focus back of empty container

- semcore/popper/__tests__/popper.browser-test.tsx
- semcore/popper/__tests__/stands/disablePortal.tsx
- semcore/popper/__tests__/stands/dropdown.tsx
- semcore/popper/src/Popper.jsx
- semcore/utils/src/use/useFocusLock.ts
- vitest.config.ts
If developer disables popper portal, popper prevents blur event to bubble of it. It's critical for work of focus lock, so I've added synthetic events in focus lock and made popper to forward it when it prevents specific event from bubbling. 
I have added focus lock browser tests and covered disabledPortal caase.
> [86bxxhdzg][utils, popper] made focus lock to work in popper with disabled portal

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/translations/de.json
- semcore/date-picker/src/translations/es.json
- semcore/date-picker/src/translations/fr.json
- semcore/date-picker/src/translations/it.json
- semcore/date-picker/src/translations/ja.json
- semcore/date-picker/src/translations/ko.json
- semcore/date-picker/src/translations/nl.json
- semcore/date-picker/src/translations/pl.json
- semcore/date-picker/src/translations/pt.json
- semcore/date-picker/src/translations/sv.json
- semcore/date-picker/src/translations/tr.json
- semcore/date-picker/src/translations/vi.json
- semcore/date-picker/src/translations/zh.json
Multiple locales where forgotten to be added to date range comparator components. This PR fixes it.
No tests needed.
> [date-picker] comparators missing locales

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
While `highlightedIndex` was clearing on dropdown menu close, `highlightedItemRef` wasn't. It was causing bug that after second reopen of DropdownMenu, the second item was highlighted instead of first.
Manually, it's enough for a such simple fix.
> [86bxxhdkq][dropdown-menu] clear highlightedItemRef on close

- semcore/popper/CHANGELOG.md
- semcore/popper/__tests__/popper.browser-test.tsx
- semcore/popper/__tests__/stands/label-referenced.tsx
- semcore/popper/__tests__/stands/label-wrapped-disable-portal.tsx
- semcore/popper/__tests__/stands/label-wrapped.tsx
- semcore/popper/src/Popper.jsx
Long time ago Select and other components were not supporting label tag clicks handling. Recently we fixed it. On the other had some of developers were wrapping Select's into labels without intention to get correct clicks handling and just for a11y tree labeling purpose.
Last case was broken by our update.
In this PR I'm adding additional checks. As we can't check if click comes from label tag I have added following check:
if trigger comes in window of 100ms after popper click and popper is a children of some of a label that is related to trigger, we should ignore this click.
With added browser tests.
> [86by5t73d][popper] fixed that Select and similar components with disabled portal were not working properly being wrapped into `label` tag

- semcore/popper/CHANGELOG.md
- semcore/popper/__tests__/index.test.jsx
- semcore/popper/__tests__/stands/disablePortal.tsx
- semcore/popper/src/Popper.jsx
- semcore/tooltip/__tests__/index.test.jsx
- semcore/tooltip/__tests__/tooltip.browser-test.tsx
Fast keyboard navigation over closely placed tooltips may cause some tooltips to stay visible even after triger blur. This PR fixes it.
I found no way to cover it with tests. I've been testing it on 4 placed next to each other tooltips with hover interaction.
> [86bxrwyxa][popper] fixed fast keyboard navigation issues

- semcore/pagination/CHANGELOG.md
- semcore/pagination/src/Pagination.jsx
When user reaches end/start of pagination using keyboard and next/prev buttons, the used button gets disabled, so the browser focus moved to body.
I've added additional check that returns focus if it lost.
Manually.
> [86by23cx5][pagination] fixed that component was loosing browser focus after reaching the last of first page with keyboard navigation

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/components/InputTrigger.jsx
- semcore/input-mask/CHANGELOG.md
- semcore/input-mask/src/InputMask.tsx
Date Picker input trigger sets width on the input mask, but alongside being applied to input, it also applied to input container that should have paddings inside. This PR fixes it by a little ad hoc.
Manually.
Before
After:
> [date-picker, input-mask] date input was trimmed a bit at the end

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Bubble.jsx
- semcore/d3-chart/src/Donut.jsx
- semcore/d3-chart/src/Hover.jsx
- semcore/d3-chart/src/Radar.jsx
- semcore/d3-chart/src/ScatterPlot.jsx
- semcore/d3-chart/src/Tooltip.jsx
- semcore/d3-chart/src/Venn.jsx
- semcore/d3-chart/src/index.js
- semcore/d3-chart/src/types/Plot.d.ts
- semcore/d3-chart/src/types/index.d.ts
- semcore/d3-chart/src/utils.ts
- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
- semcore/popper/src/index.d.ts
- semcore/utils/CHANGELOG.md
- semcore/utils/src/eventEmitter.ts
- tools/playground/src/App.tsx
- website/docs/data-display/d3-chart/d3-chart-code.md
- website/docs/data-display/d3-chart/examples/synchronous-charts.tsx
- website/docs/data-display/d3-chart/examples/tooltip-control.tsx
In this PR I'm attempted to provide an api to control over d3 chart tooltip position.
I've considered use common React approach when tooltip position is stored in React state, but then preferred imperative api with event's emitter as React state updated might be too slow and requite too much computations to handle popper position.
Current api allows developers to control tooltip visibility and position but it require for them to know and update component internal state, so I've split events into more specific ones and exposed only high level `setTooltipVisible` and `setTooltipPosition`. 
I've also found that currently d3 tooltip reinitializes popper instance on every mousemove. To fix it, I also needed to introduce small change into popper.
Manually on all affected chart types.
> [86by2hktn][d3-chart] tooltip control

- semcore/utils/CHANGELOG.md
- semcore/utils/src/themes/auto.css
- semcore/utils/src/themes/default.css
- semcore/utils/src/themes/default.json
- semcore/utils/src/themes/light.css
- semcore/utils/src/themes/light.json
- semcore/utils/theme/light.json
- website/docs/style/design-tokens/design-tokens.json
Added a new token `--intergalactic-chart-grid-period-pattern` to use as the color of stripes in the diagonal pattern for highlighting periods on a chart grid.
Manually checked that the new token was added to the list in documentation.
> Add stripe color token for diagonal chart grid pattern

- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/index.d.ts
- semcore/typography/CHANGELOG.md
- semcore/typography/src/index.d.ts
- website/docs/components/tooltip/tooltip-api.md
- website/docs/style/typography/typography-api.md
Our documentation collects types to display in global scope. So, duplication was causing displaying typography props api on the page of tooltip props api. This PR fixes it. 
I've checked locally that now correct api props are displayed on corresponding pages.
> [86bydr5qr][tooltip, typography] renamed HintProps to TooltipHintProps and TypographyHintProps to fix displaying in docs

- semcore/link/CHANGELOG.md
- semcore/link/src/Link.jsx
- semcore/link/src/style/link.shadow.css
Link was setting `disabled` and `aria-disabled` on `a` tag that is not allowed by specs.
Manually.
> [86by8dx59][link] minor a11y issues

- semcore/widget-empty/CHANGELOG.md
- semcore/widget-empty/src/WidgetEmpty.jsx
`WidgetEmpty` image already has `alt=""`, so we can safely remove `aria-hidden`. 
Adding role `status` will make `WidgetEmpty` content be announced for screen reader users.
Manually with VO.
> [86by4t5vq][widget-empty] added role status and removed aria-hidden from image

- semcore/input/CHANGELOG.md
- semcore/input/src/Input.jsx
- semcore/input/src/index.d.ts
Fixed that disabled input wasn't loosing focused state
Manually.
> [86byjmqrj][input] fixed that disabled input wasn't loosing focused state

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/MonthDateRangeComparator.jsx
- semcore/date-picker/src/components/InputTrigger.jsx
- semcore/date-picker/src/index.d.ts
* For hide Error tooltip in some cases, I've added `showError` prop to all inputs in all *Compare components
* Added render children in `MonthDateRangeComparator.RangeCalendar`
Manually
> [86byq668u][date-picker] added showError prop to inputs in comapre components

- semcore/animation/CHANGELOG.md
- semcore/animation/src/Animation.jsx
- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
- semcore/modal/__tests__/index.test.tsx
- semcore/popper/__tests__/index.test.jsx
- semcore/select/CHANGELOG.md
- semcore/select/__tests__/index.test.tsx
- semcore/select/src/Select.jsx
- semcore/utils/CHANGELOG.md
- semcore/utils/src/use/useFocusLock.ts
Our fade out mechanisms (e.g. in Modal) relies on `onAimationEnd` to be called. It's never called in tests, so in tests our Modals never closes. This PR fixes it.
I tested manually that in browser the fallback is never called.
> [86byg5qph][animation] added fallback for `onAnimationEnd` callback to be triggered even if the environment doesn't support animations

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/components/InputTrigger.jsx
Found that 
```
date.setFullYear(year);
date.setMonth(month);
date.setDate(day);
``` 
works differently from the `date.setFullYear(year, month, day);`.
And when year is 2024, month is 3 (zero-based) and day is 30, it was creating a date of May 30, 2024.
Manually.
> [86bz02uet][date-picker] fixed that some dates might shift the month when entered in the input trigger

- semcore/input-number/CHANGELOG.md
- semcore/input-number/__tests__/index.test.tsx
- semcore/input-number/src/InputNumber.jsx
It was incorrect value in `onChange` handler and in stepUp/stepDown handlers if value has more then 4 digits.
I've fixed it by adding formatting to outcoming value.
Manually and with new test
> [86bz1pmnz][input-number] fixed value format in onChange method in input number

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/src/index.d.ts
- semcore/input/CHANGELOG.md
- semcore/input/src/index.d.ts
From 18.3.3 in @types/react there are no `placeholder` in HTMLAttributes interface. So, we need to add this prop manually.
Also, I've fixed types for children render function in FeedbackForm.Item
Manually
> [86bz2ddmq][input, feedback-form] fixed some types

- semcore/scroll-area/CHANGELOG.md
- semcore/scroll-area/src/ScrollArea.jsx
Fixed logic for recalculate ScrollArea container. We should do it once if not pass `wMax` or `hMax`.
Manually
> [scroll-area] hotfix auto resizing

- .ci/lint-commit-message.ts
- tools/continuous-delivery/src/intg-release/closeTasks.ts
- tools/continuous-delivery/src/utils/allowedScopes.ts
In the previous release we've had too much task ids to close, so, I've added a little filter
Manually
> [global] added filter for tasks to close

- semcore/notice-bubble/CHANGELOG.md
- semcore/notice-bubble/src/NoticeBubble.jsx
- semcore/notice-bubble/src/utils.js
This PR fixes a rare edge case with Notice global – if notice is resizing due to inner children unmount, the cursor might found itself out of notice but MouseLeave event will not be triggered.
https://github.com/semrush/intergalactic/assets/31261408/bade3a52-fc74-44a7-bab1-41f7de8c2583
To fix it, I've added listening to the body MouseMove event when notice disappear timer is paused.
It's very hard to test, so only manually.
> [85zt70g3k][notice-bubble] fixed not called mouse leave on bubble resize

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/__tests__/index.test.tsx
- semcore/dropdown-menu/src/DropdownMenu.jsx
DropdownMenu has a mechanism to focus the trigger after the change of visibility from visible to hidden. But it also happens on the component mount if it's just hidden and wasn't visible. This PR fixes it. 
Manually and with added unit test.
> [86bz5pzaa][dropdown-menu] fixed unexpected autofocus

- semcore/dropdown/CHANGELOG.md
- semcore/dropdown/src/Dropdown.jsx
- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
- website/docs/components/counter/examples/counter_in_forms.tsx
I've added possibility to open `focusable` popper by click on it (if the trigger is already focused).
Manually
> [86bz79uec][popover, dropdown] Fix focusable popovers

- semcore/skeleton/CHANGELOG.md
- semcore/skeleton/src/Skeleton.jsx
Little fix on how we render screen reader text on elements other then svg in Skeleton
Manually
> [86bz683f5][skeleton] fixed Error about foreignObject on elements other than svg

- semcore/ellipsis/CHANGELOG.md
- semcore/ellipsis/src/Ellipsis.tsx
We didn't include few font settings in calculation width login in `Ellipsis`. I've fixed it.
Manually
> [86bz5nx20][ellipsis] fixed incorrect calculation of text width with font settings

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Body.tsx
I've added passing for datatable.body ref to a scroll.container
Could be useful to manually set focus on table body
```
...
someHandle = () => {
const tableBody = this.bodyRef.current;
if (tableBody) {
tableBody.tabIndex = 0;
tableBody.focus();
tableBody.tabIndex = -1;
}
};
...
<DataTable.Body ref={this.bodyRef} />
...
```
Manually
> [86bz53qtf][data-table] added passing ref to table.body to a scroll.container

- semcore/notice-bubble/CHANGELOG.md
- semcore/notice-bubble/src/NoticeBubbleManager.js
- semcore/notice-bubble/src/index.d.ts
- website/docs/components/notice-bubble/examples/reload_action.tsx
- website/docs/components/notice-bubble/examples/undo_action.tsx
This PR simply adds essential apis to notice bubble – function that sets focus on it and ref, both returned by the `add()` method of notice bubble manager.
Manually.
> [86bz0343c][notice-bubble] ref and focus api

- semcore/skeleton/CHANGELOG.md
- semcore/skeleton/src/Skeleton.jsx
- semcore/spin/CHANGELOG.md
- semcore/spin/src/Spin.jsx
It was found that latest screen reader doesn't announce aria-live elements on first mount. So, having `foreginObject` has no sense.
This PR should be merged alongside PR with documentation update that asks developers to wrap spinners and skeletons into aria-live containers.
No testing required.
> [86bz7edrx][spin, skeleton] rolled back and removed foregin object with aria-live element

- semcore/breadcrumbs/CHANGELOG.md
- semcore/breadcrumbs/__tests__/index.test.tsx
- semcore/breadcrumbs/src/Breadcrumbs.jsx
I've fixed `tabIndex` value for the last(active) item in Breadcrumbs.
Manually + added unit test
> [86bzfnn98][breadcrumbs] fixed last item non focusable

- semcore/input-number/CHANGELOG.md
- semcore/input-number/__tests__/index.test.tsx
- semcore/input-number/src/InputNumber.jsx
I've fixed display numbers with formatting and decimal dot, like `1,234.` and decimal parts, starts from zero `1,234.001`
Manually + added unit test
> [86bzgqayy][input-number] some fixes in formatting numbers

- website/docs/components/input/examples/input_with_a_submit_icon.tsx
- website/docs/components/input/examples/input_with_a_text_addon.tsx
- website/docs/components/input/examples/input_with_multiple_addons.tsx
- website/docs/components/input/examples/input_with_other_component_inside.tsx
- website/docs/components/input/examples/input_with_the_clearing_ability.tsx
- website/docs/components/input/examples/password_input.tsx
This PR includes important fixes in Input examples a11y. No changes were made in the component itself.
Manually.
> [86byh36gp][docs] fixed input examples a11y

- pnpm-lock.yaml
- semcore/illustration/CHANGELOG.md
- semcore/illustration/package.json
- semcore/illustration/transform.ts
- website/docs/style/illustration/examples/basic-usage.tsx
- website/docs/style/illustration/examples/custom-color.tsx
- website/docs/style/illustration/illustration-api.md
- website/docs/style/illustration/illustration-code.md
I've allowed to customize primary color of colorful illustrations with design tokens support.
Manually on added example.
> [86bz5nzey][illustration] added color prop that allow to change primary color of colorful illustrations

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Body.tsx
- semcore/skeleton/CHANGELOG.md
- semcore/skeleton/src/Skeleton.jsx
- semcore/skeleton/src/index.d.ts
Fixed displaying of bottom scroll in the table.
Added logic to automatically recalculate the skeleton width when the parent size changes.
Manually
> [86bzjpwd7][table,skeleton] fixed bottom scroll in table, added resizeObserver for the parent element in skeleton

- semcore/illustration/CHANGELOG.md
- semcore/illustration/transform.ts
- website/docs/style/illustration/examples/custom-color.tsx
- website/docs/style/illustration/illustration-code.md
This PR tries to catch on adding secondary color prop to illustration in before the upcoming release.
Manually on added example.
- x ] I have updated the documentation accordingly or it's not required.
> [illustration] added secondary color support

- website/docs/components/auto-suggest/auto-suggest-a11y.md
1. Fixed the keyboard behavior description.
2. Removed the radio/checkbox reference, as it seems it's unnecessary here.
3. Instead added a link to the Select guide.
4. Removed the link to "a11y style guide", because it's about other type of select, doesn't seem relevant to autosuggest.
5. Removed the duplicate of the link to the "popper keyboard control" guide.
> [docs] Autosuggest a11y tab update

- website/docs/components/fullscreen-modal/fullscreen-modal-a11y.md
- website/docs/components/modal/modal-a11y.md
- website/docs/components/side-panel/side-panel-a11y.md
- website/docs/components/tooltip/tooltip-a11y.md
1. Updated DescriptionTooltip default a11y properties (due to popper's role having been changed to "dialog").
2. Made `role=dialog` and `aria-modal` descriptions consistent on several component a11y pages.
> Update tooltip a11y final

- semcore/scroll-area/CHANGELOG.md
- semcore/scroll-area/src/ScrollArea.jsx
In some case with decimal value of height or width we could have recursion in calculation in scroll area. I've added some round for fix it.
Manually
> [86bzk6bje][scroll-area] fixed glitches if parend element has decimal value of height or width

- semcore/utils/CHANGELOG.md
- semcore/utils/src/focus-lock/focusBorders.ts
This PR fixes bug that in firefox focus lock with a single focusable element was allowing user focus to get our of the web page. 
This edge case is not testable with playwright as the keydown event should go to the browser window and and not just to page.
> [86bzgv4by][utils] firefox focus escape

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
- semcore/scroll-area/CHANGELOG.md
- semcore/scroll-area/src/ScrollBar.jsx
- semcore/scroll-area/src/index.d.ts
- semcore/scroll-area/src/index.js
To meet format requirements of a11y cehcking we need to hide from screen readers scrollbars that are placed inside of listboxes.
Manually with axe web extention.
> [86bzmgp7x][scroll-area, dropdown-menu] hid scrollbars from screen readers in listboxes

- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/Tooltip.jsx
Tooltip wraps popper into additional layer that already has z-index. We need this wrapper cause otherwise VO reads tooltip content twice. So, to remove too high z-index of inner popper (that is tooltip z-index + popper z-index) I've enforced clear of it.
Manually.
> [86bzuxqyt][tooltip] fixed too high z-index of tooltip

- semcore/accordion/CHANGELOG.md
- semcore/accordion/src/Accordion.jsx
- website/docs/components/accordion/examples/basic_usage.tsx
- website/docs/components/accordion/examples/custom_styles.tsx
- website/docs/components/accordion/examples/non_compact.tsx
- website/docs/components/accordion/examples/one_section_opening.tsx
- website/docs/components/inline-edit/examples/simple_use.tsx
I've changed the Accordion examples to properly use `aria-*` attributes on the toggle.
Manually
> [86bzxrcv5][accordion] fixed aria-atttributes for toggel element

- website/docs/components/tooltip/examples/basic_usage.tsx
A tiny fix in the DescriptioinTooltip example, adding a "role=button" to the Hintlink acting as a DescriptionTooltip.Trigger.
_I have a feeling I've already commited this edit in another PR, don't be surprised if you come across the same edit elsewhere %)_
Manually, with Firefox a11y inspector.
> [docs] Added button role to DescriptionTooltip Hintlink trigger

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/src/component/feedback-rating/FeedbackRating.tsx
- semcore/notice/__tests__/index.test.jsx
- semcore/notice/src/Notice.jsx
- semcore/notice/src/NoticeSmart.jsx
- semcore/notice/src/index.d.ts
- website/docs/components/notice/examples/custom_notice.tsx
- website/docs/components/notice/notice-a11y.md
- website/docs/components/notice/notice-api.md
- website/docs/components/notice/notice.md
- website/docs/patterns/feedback-rating/feedback-rating-a11y.md
- website/docs/patterns/feedback-yes-no/examples/feedbackyesno-example.tsx
As we already have projects with `Notice.CloseIcon`, I marked it as deprecated and added new `Notice.Close` component with button styles.
Manually
> [notice] added new component(Button) for close, deprecated old(Icon)

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
Fixed that behavior:
https://github.com/user-attachments/assets/f6c5b4f1-cd81-4365-b1b5-fd9f2bd8847e
Manually, can't test it automatically.
> [86bxfjmxr][dropdown-menu] added default timeout for interaction hover to fix infinite blinking

- pnpm-lock.yaml
- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/style/tooltip.shadow.css
- website/docs/components/breadcrumbs/examples/usage_example.tsx
It was found that tooltips wasn't showing in breadcrumbs example. I found a weird css code that relies on `data-popper-reference-hidden`. I can't understand the point of this attr – will se if tests are not broken.
Also I replaced tooltips with ellipsis, to use more correct aria attributes and show popper only when text is cut.
Manually.
> [86c00j9tv][tooltip] in some rare edge cases, tooltip were not appearing, also tooltip with ellipsis in breadcrumbs example

- semcore/utils/CHANGELOG.md
- semcore/utils/src/focus-lock/isFocusable.ts
Our utils concerns hiddne elements as focusable ones. It breaks "skip to content after plot" mechanism in d3 charts if any elemtns after the chart are invisible.
Manually.
> [86c06fdzp][utils] fixed that hidden elemts might be considered as focusable

- semcore/side-panel/CHANGELOG.md
- semcore/side-panel/src/SidePanel.jsx
The animation delay was added for an unclear purpose. Probably to show backdrop before side panel. I have remvoed it and now close animation is nor fragmented and feels much better.
Manually.
> [86c09aw3f][side-panel] removed animation delay

- semcore/utils/CHANGELOG.md
- semcore/utils/src/getEventTarget.ts
Event target util was unable to get event target if event happend inside of nested document.
Manually on this snippet:
```
import React from 'react';
import data from '@emoji-mart/data';
import { BaseEmoji, Picker } from 'emoji-mart';
import { FC, useEffect, useRef } from 'react';
import Button from 'intergalactic/button';
import Dropdown from 'intergalactic/dropdown';
const RenderPicker: FC = () => {
const ref = useRef<HTMLDivElement>(null);
useEffect(() => {
if (!ref.current?.innerHTML) {
new Picker({
data,
ref,
});
}
}, []);
return <div ref={ref} />;
};
const AddEmojiButton = () => (
<div>
<Dropdown>
<Dropdown.Trigger tag={Button}>Emoji picker</Dropdown.Trigger>
<Dropdown.Popper>
<div>Area where outside click works well</div>
<RenderPicker />
</Dropdown.Popper>
</Dropdown>
<br />
<br …
```
> [86c0484a6][utils] fixed that click outside utility was considering all clicks inside of shadow root as clicks outside

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Body.tsx
Little fix with preventing events on table cells with focusable elements.
Manually
> [86c0fvubu][data-table] Fixed preventing defaults and propagation for pressing Enter on TableCell with focusable elements

- semcore/switch/CHANGELOG.md
- semcore/switch/src/Switch.jsx
I just changed the animation triggers to work correctly in popups (because the portal has stopPropagation for all events, and the newly added events do not work)
Manually
> [86c0gvr1h][switch] fixed animations in popovers

- website/docs/components/select/select-a11y.md
- website/docs/components/select/select-code.md
Apparently, I forgot to write about the listbox vs dialog logic in the a11y docs. Added this info now.
Will be nice to publish this update before the announcement is posted.
> [docs] Added dialog vs listbox info to Select a11y docs

- semcore/ellipsis/CHANGELOG.md
- semcore/ellipsis/src/Ellipsis.tsx
- website/docs/components/card/examples/ellipsis.tsx
Fixed showing tooltip in the middle cropped ellipsis
Manually
> [86c0r63f1][ellipsis] fixed logic of showing tooltip for trimmed in the middle texts - show only for cropped

- semcore/modal/CHANGELOG.md
- semcore/modal/src/style/modal.shadow.css
I moved SClose button class in SWindow for prevent rewrite them from another styles
Manually
> [modal] changed added selector specificity for modal close button

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/DataTable.tsx
We've incorrectly set focus to table after interaction with mouse with some elements inside it. I've fixed it.
Manually
> [UIK-2541][data-table] fixed unexpected focusing on the first element of table after first clicking on some interactive element inside it

- semcore/mini-chart/CHANGELOG.md
- semcore/mini-chart/src/component/score/Donut.tsx
- semcore/mini-chart/src/component/score/Line.tsx
- semcore/mini-chart/src/component/score/Score.ts
- semcore/mini-chart/src/component/score/line.shadow.css
- website/docs/data-display/mini-chart/examples/base_color.tsx
- website/docs/data-display/mini-chart/mini-chart-code.md
Added `baseBgColor` option to specify pass second color as background for TrendLine and ScoreDonut
manually
> [UIK-2204][mini-chart] add option to pass second color

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/index.d.ts
- semcore/dropdown/CHANGELOG.md
- semcore/dropdown/src/index.d.ts
- semcore/popper/__tests__/stands/disable-portal.tsx
- semcore/popper/__tests__/stands/dropdown.tsx
- semcore/select/__tests__/index.test.tsx
- website/docs/components/dropdown-menu/dropdown-menu-a11y.md
- website/docs/components/dropdown-menu/dropdown-menu-code.md
- website/docs/components/dropdown-menu/examples/dropdown-menu.tsx
- website/docs/components/dropdown-menu/examples/nested-with-focusable.tsx
- website/docs/components/input-phone/examples/known_country_and_number_format.tsx
- website/docs/components/select/examples/advanced_filtering_control.tsx
- website/docs/components/select/examples/dropdownmenu_customization.tsx
- website/docs/components/select/examples/options_filtering.tsx
- website/docs/components/select/select-a11y.md
- website/docs/data-display/d3-chart/examples/export-to-image.tsx
- website/docs/filter-group/filter-serp-features/examples/serp-filter.tsx
- website/docs/patterns/validation-form/examples/form-validation-example-by-`unfocus`.tsx
- website/docs/table-group/data-table/examples/export-in-image.tsx
I added required aria-* props for `Select.Popper` and `DropdownMenu.Popper` if they has role `dialog`.
Manyally
> [UIK-2201][dropdown, dropdown-menu] added DropdownPopperAriaProps for dialogs

- website/docs/patterns/validation-form/validation-form-a11y.md
- website/docs/patterns/validation-form/validation-form-code.md
- website/docs/patterns/validation-form/validation-form.md
Validation pattern example had the same functionality as Form example.
I removed Validation example from the Example page and replaced it with a link to Form.
Also fixed some small issues in text.
> [UIK-2631][docs] Replaced Validation example with link to Form, linted texts

- semcore/link/CHANGELOG.md
- semcore/link/src/Link.jsx
- stories/components/link/docs/examples/color_links.tsx
- stories/components/link/docs/examples/link_addon.tsx
- stories/components/link/docs/examples/link_as_button.tsx
- stories/components/link/docs/examples/link_disabled.tsx
- stories/components/link/docs/examples/link_inside_the_content.tsx
- stories/components/link/docs/examples/link_without_text.tsx
- stories/components/link/docs/examples/links_with_ellipsis.tsx
- stories/components/link/docs/link.stories.tsx
- website/docs/components/link/link-code.md
I added render as a Hint to all Link if there are only addon and no children
Manually
> [UIK-2217][link] fixed render hint's popper on Link with addonLeft as props and no children

- stories/patterns/ux-patterns/confirmation-modal-dialog/docs/__tests__/ConfirmationModalDialog.test.tsx
- stories/patterns/ux-patterns/confirmation-modal-dialog/docs/examples/confirmation-modal-example.tsx
Removed `aria-errormessage` from input in ConfirmationModal example.
Fixes double Error Tooltip reading in NVDA.
Also, `aria-describedby` connects to Tooltip, only when Tooltip is in the DOM
manually with VO and NVDA
> [UIK-3022][stories, docs] remove aria-errormessage from confirmation modal example

- website/docs/core-principles/motion-principles-guide/easing.module.css
- website/docs/core-principles/motion-principles-guide/motion-principles-guide.md
I commented out the Easings section on the Motion page, because its value isn't clear right now. 
We don't use custom bezier timing functions, and the example didn't use our Animation component, so it didn't show anything useful in context of Intergalactic.
Before hiding, I made the animated blocks focusable and enabled animation on focus, for keyboard accessibility. I also added a small instruction before the example.
> [UIK-2881][docs] Hid easings section from Motion page

- semcore/grid/__tests__/grid.browser-test.tsx
i fixed test for grid - added logic for both cases when class contains 1 span and 2 spans (because sometimes class has 2 spans like  ___SCol_3xc3r_gg_ __span_3xc3r_gg_ _span_1_3xc3r_gg_ _offset_11_3xc3r_gg_, sometimes with 1 span like  - ___SCol_3xc3r_gg_ _span_1_3xc3r_gg_ _offset_11_3xc3r_gg_ )
> [grid] fix test

- semcore/slider/CHANGELOG.md
- semcore/slider/__tests__/slider.browser-test.tsx
- semcore/slider/src/Slider.jsx
- stories/components/slider/docs/examples/numeric_slider.tsx
When a user entered a value greater than the slider's maximum via the input field, the slider knob did not clamp to the maximum value. Additionally, when the knob was focused, pressing the Left Arrow key did not decrease the value as expected.
This fix ensures the value is clamped to the maximum if the input exceeds it, and that the knob responds correctly to arrow key navigation.
It's been tested manually.
> [slider] fix issue with value > max not clamping or decreasing on key

- pnpm-lock.yaml
- website/package.json
Two key dependencies used for search (`@docsearch/js` and `@docsearch/css`) were updated from `3.6.1` to `3.9.0`.
These packages are dependencies of `vitepress`, and their versions were specified with a caret (`^3.6.0`), which allows automatic upgrades to compatible versions — including `3.9.0`.
It's been tested manually.
> [UIK-3843][website] fixed @docsearch versions

- semcore/flags/CHANGELOG.md
- semcore/flags/src/countries.json
- semcore/flags/src/index.d.ts
We already had the EU flag in the assets, but we didn't have a corresponding code in the ISO2 list.
I just added "EU" to the ISO2 list. Even though EU isn't part of ISO 3166-1 alpha-2, it's an "exceptional reservation", which should mean that it won't be assigned to anything else, so it's safe to use as a code for European Union.
Manually. EU flag now appears on [the example page](http://localhost:5173/intergalactic/components/flags/flags).
> [UIK-3841] added EU to iso2 codes

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/components/Body/Body.tsx
- semcore/data-table/src/components/Body/Body.types.ts
- semcore/data-table/src/components/Body/Cell.tsx
- semcore/data-table/src/components/Body/Cell.types.ts
- semcore/data-table/src/components/DataTable/DataTable.tsx
- semcore/data-table/src/components/Head/Column.tsx
- semcore/data-table/src/components/Head/Column.types.ts
- semcore/data-table/src/components/Head/Head.tsx
- semcore/data-table/src/components/Head/Head.types.ts
We have and internal `focusedCell` in the Table, so, I added logic to set in it clicked cell.
Manually
> [UIK-3858][data-table] Fixed interact with the table using the keyboard after clicking the mouse in a certain cell

- website/docs/.vitepress/theme/VPSidebarItem.vue
When navigating to a page using an internal link from another section, the corresponding section in the menu remained collapsed.
The fix ensures that the correct section is automatically expanded upon navigation.
It's been tested manually.
> [UIK-3824][website] fixed correct section expanding on internal navigation

- website/docs/.vitepress/renderLoomVideo.ts
- website/docs/get-started-guide/dis-starter-guide/dis-starter-guide.md
- website/docs/get-started-guide/work-figma/work-figma.md
Changed our custom `loom_video` plugin to insert specified title into the iframe.
Now loom videos should be embedded like this:
_(title is optional, default one is "video")_
For existing videos on our website, I copied titles from the videos themselves, as per [Axe's recommendation](https://dequeuniversity.com/rules/axe/4.10/frame-title-unique):
> best practice is to give the enclosed document a title element with content identical to the title attribute. Some screen readers will replace the contents of the title attribute on the frame with the contents of the title element inside the frame. As a result, it’s safest and most accessible to have the same text in both locations.
> [UIK-3523][website] added unique titles for Loom frames

- semcore/slider/CHANGELOG.md
- semcore/slider/__tests__/slider.browser-test.tsx
- semcore/slider/src/Slider.jsx
The `Slider` doesn't handle Home and End keyboard keys, which are expected to move the thumb to the minimum and maximum values, respectively.
This fix adds proper keyboard handling.
It's been tested manually + uncommented lines which check this case.
> [UIK-3603][slider] fixed support for Home and Key key navigation

- semcore/core/CHANGELOG.md
- semcore/core/src/core-types/Component.ts
- semcore/core/src/coreFactory.tsx
- semcore/d3-chart/src/Tooltip.jsx
- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/Tooltip.jsx
Manually and with existing tests
> [tooltip] fixed incorrect sybmols link if Popper and Tooltip has different core package

- semcore/ellipsis/src/Ellipsis.tsx
I changed the usage of two different components (Tooltip and Box) to one `Tooltip` always with disabling its behavior via interaction . This fixed a bug in `useResizeObserver` that did not track the change of the ref. But I thought it was more logical to leave the only one component and just change its behavior via props.
Manually
> [UIK-3879][ellipsis] fixed trim=middle behavior

- semcore/pagination/CHANGELOG.md
- semcore/pagination/__tests__/pagination.browser-test.tsx
- semcore/pagination/src/Pagination.jsx
In Safari, focus is lost when using `Next`/`Prev` buttons to reach the first or last page. The fix ensures focus remains on the buttons.
I've updated browser test.
> UIK-3282/focus loss in safari pagination

- website/docs/.vitepress/theme/Sandbox.vue
Removed the logic that replaced "intergalactic" with "semcore/ui" in our Sandboxes (because we don't have intergalactic imports anymore, and that replacement broke rendering of urls containing "intergalactic").
> [website] removed replacing intergalactic with semcore in sandboxes

- semcore/data-table/CHANGELOG.md
- semcore/data-table/__tests__/data-table-header.browser-test.tsx
- semcore/data-table/src/components/Head/Column.tsx
- stories/components/data-table/tests/examples/header-tests/sorting-default-undefined.tsx
`onSortChange` is triggered twice on a single sort action. The fix ensures it fires only once.
Manually
> [UIK-4079][data-table] prevent double call of onSortChange
