- semcore/select/src/index.d.ts
Fixed Select component's generic for onChange
> [Select] typings fix

- semcore/d3-chart/src/Area.js
- semcore/d3-chart/src/Line.js
- semcore/d3-chart/src/utils.js
- yarn.lock
Иногда линии с данными прерываются так как данных больше нет. Если это одна линия, то не проблема так как заканчивается массив с данными, но если несколько линий и одна из них закончилась, то в нее данные необходимо передавать undefined.
Не пусть undefined и null, второй необходим для построения пунктира.
> [D3-CHART] Add ability 'undefined' for data

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Bar.js
- semcore/d3-chart/src/GroupBar.js
- semcore/d3-chart/src/HorizontalBar.js
- semcore/d3-chart/src/StackBar.js
- semcore/d3-chart/src/StackedArea.js
- semcore/d3-chart/src/types/Bar.d.ts
- semcore/d3-chart/src/types/HorizontalBar.d.ts
Изменил апи, что бы принимал массив радиусов.
Написал функцию вычисления в стекбаре
> Fix bar radius

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/__tests__/index.test.js
- semcore/dropdown-menu/src/DropdownMenu.js
- semcore/dropdown/__tests__/index.test.js
enter space in input trigger
added tests for this
> [DropdwonMenu] fixed enter space in input trigger

- website/docs/style/themes/themes-global.md
> edit themes-global.md

- .github/workflows/publish-release.yml
- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-11.0.0

- semcore/input-tags/CHANGELOG.md
- semcore/input-tags/src/InputTags.tsx
- website/docs/components/form/examples/inputTags&select.jsx
- website/docs/components/form/examples/reactHookForm.jsx
- website/docs/components/input-tags/examples/basic.jsx
- website/docs/components/input-tags/examples/enter-url.jsx
Successor of https://github.com/semrush/intergalactic/pull/127
> [input-tags] callback called with multiple arguments on batch change

- website/docs/data-display/area-chart/area-chart.md
- website/docs/data-display/bar-chart/bar-chart-vertical.md
- website/docs/data-display/bar-chart/bar-chart.md
- website/docs/data-display/bar-horizontal/bar-horizontal.md
- website/docs/data-display/bubble-chart/bubble-chart.md
- website/docs/data-display/data-display.md
- website/docs/data-display/donut-chart/donut-chart.md
- website/docs/data-display/histogram-chart/histogram-chart.md
- website/docs/data-display/line-chart/line-chart.md
- website/docs/data-display/radial-tree-chart/radial-tree-chart.md
- website/docs/data-display/scatterplot-chart/scatterplot-chart.md
- website/docs/data-display/stacked-area-chart/stacked-area-chart.md
- website/docs/data-display/stacked-bar-chart/stacked-bar-chart.md
- website/docs/data-display/venn-chart/venn-chart.md
- update guides order
- fix some inconsistencies in chart guides
> [chart] update guides order, fix inconsistencies

- semcore/slider/CHANGELOG.md
- semcore/slider/src/index.d.ts
> [slider] fix type for knob and bar

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-11.2.0

- semcore/table/CHANGELOG.md
- semcore/table/src/StickyHead.jsx
Prevent memory leak when component was unmounted but function with throttle doesn't canceled
> fixed memory leak by cancel function with throttling

- semcore/progress-bar/CHANGELOG.md
- semcore/progress-bar/src/ProgressBar.jsx
- semcore/progress-bar/src/style/progress-bar.shadow.css
> [progress-bar] fix theme prop

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
- semcore/utils/CHANGELOG.md
> release-after-12.1.0

- semcore/utils/CHANGELOG.md
- semcore/utils/style/var.css
- website/docs/style/palette/components/color-group.jsx
- `--orange-400` was updated from `ff622d` to `ff642d`
- `--brand-color` was updated from `ff622d` to `ff642d`
- `--violet-700` was updated from `421984` to `421983`
> [utils] brand colors were tuned

- website/docs/data-display/bar-chart/examples/bar-date.jsx
- website/docs/data-display/bar-chart/examples/horizontal-recharts.jsx
- website/docs/data-display/bar-chart/examples/positive-negative-recharts.jsx
- website/docs/data-display/bar-chart/examples/simple-recharts.jsx
- website/docs/data-display/bar-horizontal/examples/horizontal-recharts.jsx
- website/docs/data-display/chart-controls/examples/selected.jsx
- website/docs/data-display/d3-chart/examples/responsive.jsx
- website/docs/data-display/histogram-chart/examples/simple-recharts.jsx
- website/docs/data-display/line-chart/examples/start-recharts.jsx
- website/docs/data-display/stacked-bar-chart/examples/stacked-recharts.jsx
- website/docs/data-display/venn-chart/examples/basic-recharts.jsx
- website/docs/data-display/venn-chart/examples/orientation-and-order-recharts.jsx
- website/src/components/Example.module.css
Fixed display of examples in Chart and DataTable, because they are not displayed correctly when the container is not width 100%.
> Example container

- .eslintignore
- tools/babel-plugin-react-semcore/__tests__/__fixtures__/theme/applied/index.expected.js
- tools/babel-plugin-react-semcore/__tests__/__fixtures__/theme/applied/index.js
- tools/babel-plugin-react-semcore/__tests__/__fixtures__/theme/purgeCSS/index.expected.js
- tools/babel-plugin-react-semcore/__tests__/__fixtures__/theme/purgeCSS/index.js
- tools/babel-plugin-react-semcore/__tests__/__fixtures__/theme/unchanged/index.expected.js
- tools/babel-plugin-react-semcore/__tests__/__fixtures__/theme/unchanged/index.js
- tools/babel-plugin-react-semcore/__tests__/index.test.js
- tools/babel-plugin-react-semcore/package.json
- tools/babel-plugin-react-semcore/src/process.js
- tools/babel-plugin-styles/CHANGELOG.md
- tools/babel-plugin-styles/package.json
- tools/babel-plugin-styles/src/index.js
- tools/babel-plugin-styles/src/postcss-shadow-styles.js
- yarn.lock
Container reshadow hash and class hash are now the same.
Also, the hash now does not depend on the path in the system.
> Change generate style hash

- semcore/dropdown-menu/CHANGELOG.md
- semcore/fullscreen-modal/CHANGELOG.md
- semcore/icon/CHANGELOG.md
- semcore/input-number/CHANGELOG.md
- semcore/input/CHANGELOG.md
- semcore/neighbor-location/CHANGELOG.md
- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-12.3.0

- package.json
- website/Dockerfile
- website/cloudbuild.yaml
> TEST preview site for pull request

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-12.4.0

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-12.4.1

- .github/PULL_REQUEST_TEMPLATE.md
Updated Pull request template to the new one without long checklists that were almost never used.
Our current pull request template sucks – almost nobody was using this checkbox lists. 
Also these lists were really long and not suitable for 99% pull requests.
I have took a look into https://github.com/stevemao/github-issue-templates and picked the most pleasant one (subjectively)
> [chore] updated pr template

- semcore/data-table/__tests__/index.test.tsx
- semcore/data-table/src/Body.tsx
- semcore/data-table/src/DataTable.tsx
- semcore/data-table/src/Head.tsx
Signed-off-by: r.lysov <r.lysov@semrush.com>
🦄...
> [data-table] Add roles

- semcore/link/CHANGELOG.md
- semcore/link/src/Link.jsx
- website/docs/components/link/examples/a11y.jsx
- website/docs/components/link/link-a11y.md
- website/docs/components/link/link-code.md
> [link] added accessibility

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-12.4.2

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/__tests__/index.test.jsx
- semcore/feedback-form/src/FeedbackForm.jsx
- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/Tooltip.jsx
- website/docs/components/feedback-yes-no/examples/feedback-yes-no.jsx
- website/docs/components/feedback/examples/feedback.jsx
added aria attributes for better accessibility
to make feedback-form component more accessible
with VoiceOver app
> [feedback-form] added more a11y

- semcore/input-tags/CHANGELOG.md
- semcore/input-tags/__tests__/index.test.tsx
- semcore/input-tags/src/InputTags.tsx
- semcore/tag/CHANGELOG.md
- semcore/tag/__tests__/index.test.tsx
- semcore/tag/package.json
- semcore/tag/src/Tag.jsx
- website/docs/components/input-tags/examples/basic.jsx
- website/docs/components/input-tags/examples/filter.jsx
- website/docs/components/tag/examples/edit-tag.jsx
- website/docs/components/tag/examples/remove-tag.jsx
- website/docs/components/tag/tag-code.md
> [tag, input-tags] added accessibility

- semcore/fullscreen-modal/CHANGELOG.md
- semcore/fullscreen-modal/src/index.d.ts
removed unused `hidden` property from types
> [fullscreen-modal] removed unused hidden property from types

- website/src/components/Header.module.css
- website/src/components/SearchHome.module.css
fixed logo layout in header as in `API` page
> [website] fixed logo layout in header

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-12.5.0

- semcore/widget-empty/CHANGELOG.md
- semcore/widget-empty/src/WidgetEmpty.jsx
Actually change is very small and not needed to be reviewed. I have opened pull request to ensure all tests pass on ci env.
> [widget-empty] made widget illustration aria-hidden now

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
- tools/super-publisher/tasks/check-git.ts
> release-after-12.5.1

- semcore/pills/CHANGELOG.md
- semcore/pills/__tests__/pills.vo-test.ts
- semcore/pills/package.json
- semcore/pills/src/Pills.jsx
- website/docs/components/pills/examples/basic.jsx
- website/docs/components/pills/pills-a11y-report.md
- website/docs/components/pills/pills-a11y.md
- website/docs/components/pills/pills-code.md
- website/docs/components/pills/pills.md
- yarn.lock
Much improved `Pills` components accessibility.
I have added essential a11y attributes to `Pills` component. Also I added the Example section in our documentation. (was surprised that there were not one)  
I found that our pills components are the same UX element to HeadlessUI radio. And adding same a11y attributes much improved components a11y.
I have added VO test and ensured that existing tests are not broken.
> [pills] a11y

- semcore/errors/CHANGELOG.md
- semcore/errors/__tests__/index.test.tsx
- semcore/errors/src/Error.jsx
- semcore/errors/src/index.d.ts
- semcore/illustration/src/index.d.ts
- semcore/illustration/src/index.js
- semcore/illustration/src/index.ts
- semcore/widget-empty/CHANGELOG.md
- semcore/widget-empty/src/WidgetEmpty.jsx
- semcore/widget-empty/src/index.d.ts
- website/docs/style/illustration/illustration-api.md
- website/docs/style/illustration/illustration.md
- yarn.lock
First part have already merged in master branch https://github.com/semrush/intergalactic/commit/3d93e4aef107021ce0058c204a78e2c4017dea27. 
In this PR there fixes and adjustments related to access to svg illustrations. 
And illustration api page was added .
> [widget-empty, errors] moved svg illustrations to @semcore/illustration component

- website/docs/internal/roadmap/components/roadmap.jsx
> [website] update roadmap page

- .github/workflows/release-pull-request.yml
- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
- tools/babel-preset-ui/.babelrc.js
> release-after-13.0.0

- semcore/ui/CHANGELOG.md
- semcore/ui/generate.ts
- semcore/ui/package.json
> release-after-13.0.1

- website/builder/utils.ts
- website/src/App.jsx
- website/src/App.module.css
- website/src/components/ComponentCard.jsx
- website/src/components/Copy.jsx
- website/src/components/DocsHeader.jsx
- website/src/components/EmailsBanner.jsx
- website/src/components/Error.jsx
- website/src/components/Footer.jsx
- website/src/components/Header.jsx
- website/src/components/ImageFromModal.jsx
- website/src/components/Sandbox.jsx
- website/src/components/SearchHome.jsx
- website/src/components/SideBarNavigation.jsx
- website/src/components/UpdateBlock.jsx
- website/src/docs-components/PlaygroundGeneration.jsx
- website/src/main.css
- website/src/pages/ContactUs.jsx
- website/src/pages/Home.jsx
- website/src/pages/Home.module.css
We have a problem with the accessibility of the site. With this pr I want to make the site more accessible to people with disabilities
> [website] fixed some accessibility issue

- pnpm-lock.yaml
- semcore/button/CHANGELOG.md
- semcore/button/package.json
- semcore/button/src/Button.jsx
- semcore/icon/CHANGELOG.md
- semcore/icon/package.json
- semcore/icon/src/Icon.jsx
- semcore/link/CHANGELOG.md
- semcore/link/package.json
- semcore/link/src/Link.jsx
- semcore/utils/CHANGELOG.md
- semcore/utils/package.json
- semcore/utils/src/hasLabels.ts
Instead of `reactToText` components now use dom traversing in a browser macrotask. 
In some cases `reactToText` misses text that appear in DOM and also blocks component rendering.
I have tested warning on all affected components
> [button, icon, link] lazy checks for necessity of aria-label in non roduction environment

- pnpm-lock.yaml
- semcore/modal/CHANGELOG.md
- semcore/modal/package.json
- semcore/popper/CHANGELOG.md
- semcore/popper/package.json
- semcore/select/__tests__/autoSuggest.vo-test.ts
- semcore/side-panel/CHANGELOG.md
- semcore/side-panel/package.json
Just need to run CI checks before pushing to master.
> [global] updated focus-lock

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-13.0.2

- semcore/checkbox/src/style/checkbox.shadow.css
- semcore/dot/CHANGELOG.md
- semcore/dot/src/style/dot.shadow.css
- semcore/pills/CHANGELOG.md
- semcore/pills/src/style/pills.shadow.css
Added css property `isolation` to container because these components have `z-index` which can create problems in certain scenarios with overlapping content.
> [pills, dot] added css property isolation to container

- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
> release-after-13.1.1

- website/docs/patterns/validation-form/validation-form.md
> fixed a typo and sentence structure

- website/docs/patterns/web-performance/web-performance.md
> added a space

- website/docs/patterns/informer/informer.md
> Documentation: typo

- semcore/input-tags/src/InputTags.tsx
- semcore/notice-bubble/src/index.d.ts
Fixed errors:
- Component has invalid typing, component itself was wrapped in props generic object
- NoticeBubbleManager class was described as `implements Interface`, but methods of this interface were not implemented in class definition. This caused compilation error on `typescript@^4.9`.
My build is broken 😅
> Components typings fixes

- website/docs/components/notice-bubble/notice-bubble.md
Changed headings wording. Previous ones seemed kinda harsh and a bit unclear. Feel free to rewrite further, if you have other ideas.
Changed headings wording. Previous ones seemed kinda harsh and a bit unclear. Feel free to rewrite further, if you have other ideas.
> (documentation) Changed wording

- website/docs/components/notice-bubble/notice-bubble.md
Fixed a typo and sentence structure in component documentation.
> (documentation) typo and sentence structure

- website/docs/get-started-guide/dev-starter-guide/dev-starter-guide.md
Signed-off-by: r.lysov <r.lysov@semrush.com>
Changed the description of the start page for developers
Removed some sections as they should not be at the beginning of the tutorial.
Added sections that I consider important
Run docs
> [docs] Change get started page

- semcore/tag/CHANGELOG.md
- semcore/tag/src/style/tag.shadow.css
Fix CSS syntax error
Broken library consumers build
None
> [tag] fix css syntax error

- website/docs/components/sticky/sticky.md
- website/docs/product-emails/badge-email/badge-email.md
- website/docs/product-emails/button-email/button-email.md
- website/docs/product-emails/core-email/core-email.md
- website/docs/product-emails/divider-email/divider-email.md
- website/docs/product-emails/grid-email/grid-email.md
- website/docs/product-emails/notice-email/notice-email.md
- website/docs/product-emails/product-emails.md
- website/docs/product-emails/summary-email/summary-email.md
- website/docs/product-emails/table-email/table-email.md
- website/docs/product-emails/typography-email/typography-email.md
- website/docs/table-group/table-old/table-old.md
- website/src/components/DocsHeader.jsx
- website/src/components/DocsHeader.module.css
- website/src/components/SideBarNavigation.jsx
- website/src/components/SideBarNavigation.module.css
- website/src/pages/Home.jsx
- website/src/pages/Home.module.css
- website/src/pages/Page.jsx
> [website] mark deprecated components on the site

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Donut.jsx
Fixed `Donut` chart rendering when hovering over a chart while it is loading.
> [d3-chart] fixed Donut chart rendering

- website/docs/components/modal/modal.md
Fixed an inconsistency. The word "data" was used in both singular and plural forms. Left the singular form.
> [docs] Grammar in Modal documentation

- website/docs/components/notice/notice.md
> [docs] Notice - grammar fixes

- pnpm-lock.yaml
- website/package.json
- website/src/components/AllComponents.jsx
- website/src/pages/Home.jsx
This `Masonry` lib add additional styles on main page that we don't need because it cut of words in some screen resolution (please see screenshot).
To have better and clear ui.
By changing screen resolution with zoom and dev tools.
> [website] removed lib Masonry to have more clear styles on main page

- pnpm-lock.yaml
- semcore/modal/CHANGELOG.md
- semcore/modal/package.json
- semcore/modal/src/Modal.jsx
- semcore/modal/src/index.d.ts
- semcore/modal/src/modal.vo-test.ts
- semcore/modal/src/style/modal.shadow.css
- website/docs/components/modal/examples/modal.jsx
- website/docs/components/modal/modal-api.md
- website/docs/style/design-tokens/components/design-tokens.json
Added new component `Modal.Title` that adds `aria-labelledby` attribute for better a11y.
To make a11y better.
By eyes and by checking attributes and tags in dev tools.
> [modal] added component Title

- semcore/ellipsis/CHANGELOG.md
- semcore/ellipsis/__tests__/index.test.tsx
- semcore/ellipsis/src/Ellipsis.tsx
If the text is not truncated, then do not show the tooltip and duplicate the text
We missed this point in initial development 🤷‍♂️
I wrote tests. But you can also run in the playground
> [ellipsis] Don't show tooltip if it's not needed 

- website/docs/components/feature-popover/feature-popover.md
Signed-off-by: ivoninskii <25663530+ivoninskii@users.noreply.github.com>
Small edits in feature-popover.md
> Small edits in feature-popover.md

- pnpm-lock.yaml
- website/package.json
- website/src/App.jsx
- website/src/utils/amplitude-client.js
- website/src/utils/amplitude.ts
Added amplitude app for logging events and collect analytics on website
> [website] added amplitude

- website/src/components/AllComponents.jsx
- website/src/components/ComponentCard.jsx
- website/src/components/Copy.tsx
- website/src/components/Docs.jsx
- website/src/components/DocsHeader.jsx
- website/src/components/Example.jsx
- website/src/components/Header.jsx
- website/src/components/Sandbox.jsx
- website/src/components/SearchHome.jsx
- website/src/components/SideBarHeading.jsx
- website/src/components/SideBarNavigation.jsx
- website/src/pages/Home.jsx
- website/src/pages/Page.jsx
- website/src/utils/amplitude-client.js
- website/src/utils/amplitude.ts
Added amplitude events to track analytic on website
> [website] added amplitude events for analytic

- website/docs/core-principles/core-principles.md
- website/docs/core-principles/motion-principles-guide/components/easing.jsx
- website/docs/core-principles/motion-principles-guide/components/easing.module.css
- website/docs/core-principles/motion-principles-guide/motion-principles-guide.md
Documentation by @tatana-I with visual easing widget. 
Recently an animation release was rolled out, we need a better documentation about our motion principles.
> [docs] added motion page

- pnpm-lock.yaml
- website/builder/build-article/build-article.ts
- website/package.json
- website/src/components/Changelog.jsx
- website/src/components/ChangelogByComponent.jsx
- website/src/components/Docs.jsx
- website/src/components/DocsHeader.jsx
- website/src/components/Example.jsx
- website/src/components/Header.jsx
- website/src/components/HeadingLink.jsx
- website/src/components/Markdown.jsx
- website/src/components/SearchHome.jsx
- website/src/components/SideBarHeading.jsx
- website/src/components/SideBarNavigation.jsx
- website/src/components/TypescriptDeclaration.jsx
- website/src/pages/Page.jsx
- website/src/utils/amplitude-client.js
- website/src/utils/amplitude.ts
- Fixed some events properties.
- Added new event `init_app` with `theme` property.
- Added sending additional data of user.
> [website] fixed and added new amplitude analytics events

- semcore/animation/CHANGELOG.md
- semcore/animation/src/style/keyframes.shadow.css
Added `pointer-events` properties to scale group `keyframes` to avoid problems with overlapping elements and changing the cursor.
> [animation] added pointer-events to some keyframes

- website/builder/build-article/build-article.ts
- website/src/components/SideBar/SideBarWrapper.jsx
> [website] tried to fix website typings loading

- semcore/date-picker/src/utils/formatDate.js
Increased the performance of the **date-picker** component by optimizing the **getLocaleDate** function
Added a cache for the **Intl.DateTimeFormat** formatter function constructor as it is an **expensive** operation
There are noticeable delays in rendering
Checked the performance on the local version of the website
The measurements below will be to switch the period in the date-picker **16** times
All measurements were made using the slowdown of the processor up to **4** times
**Before**:
**After**:
> [date-picker] increased performance in getLocaleDate

- website/docs/patterns/form/form.md
A small change in the docs text to improve the language.
> form.md - small language fixes

- website/docs/patterns/form/form.md
Small change in docs to improve language.
> form.md - small language fix

- CONTRIBUTING.md
Added information about the need to install manually libpng and pkg-config on MacOS before install deps
Documentation. Don't need tests.
> [chore] added info about error with libpng to Contributing manual

- website/docs/components/spin-container/components/playground.jsx
> [website][SpinContainer] added size to SpinContainer's playground

- website/docs/components/radio/examples/group.tsx
> [website][Radio] changed view of Radio items in example to vertical list

- website/docs/components/dropdown-menu/examples/popper-list.tsx
- website/docs/components/radio/examples/group.tsx
> [Website][DropDown] GH-718 correct view in export dd example

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/types/Axis.d.ts
- semcore/d3-chart/src/types/Hover.d.ts
While making all components api strongly typed not all existing use cases had been taken into account. 
To handle them, we need to establish contract that props typed in this PR are available for use.
Manual testing in VSCode
> [d3-chart] added missing HoverLine, HoverRect, XAxis.Ticks and YAxis.Ticks cotnext props

- website/docs/data-display/donut-chart/examples/donut-with-checkbox.tsx
> [website] fixed view of donut chart in examples

- website/docs/data-display/line-chart/examples/legend.tsx
Improvement of documentation
- Correct view for Chart Legend Title
- Correct view for yAxis 
> [website] fixed view for Legend header title in examples

- website/docs/components/input-phone/examples/mask.tsx
fixed flag as Addon in Trigger, correct input width, correct clear method in example of input-phone in documentation
Improvement of documentation
> [website] fixed example of input-phone

- website/docs/components/dropdown-menu/examples/basic.tsx
> [website] fixed base example for DropDown Menu

- semcore/button/CHANGELOG.md
- semcore/button/__tests__/index.test.tsx
- semcore/button/package.json
- semcore/button/src/Button.jsx
- tools/testing-utils/setupTests.ts
- tools/testing-utils/vitest.ts
Added aria-bisy attribute for Button component
I have added unit tests
> [button] added aria-bisy for Button if it's disabled (or loading)

- website/docs/data-display/bar-chart/bar-chart.md
- website/docs/data-display/bar-horizontal/bar-horizontal.md
- website/docs/data-display/chart-legend/chart-legend.md
- website/docs/data-display/donut-chart/donut-chart.md
- website/docs/data-display/histogram-chart/histogram-chart.md
- website/docs/data-display/radar-chart/radar-chart.md
- website/docs/data-display/stacked-horizontal-bar/stacked-horizontal-bar.md
- website/docs/data-display/venn-chart/venn-chart-d3-code.md
- website/docs/data-display/venn-chart/venn-chart.md
- website/docs/get-started-guide/dis-starter-guide/dis-starter-guide.md
> [website] update dataset wording in documentation

- semcore/button/CHANGELOG.md
- semcore/utils/__tests__/index.test.tsx
- semcore/utils/src/enhances/keyboardFocusEnhance.tsx
> [button] correct focus for disabled buttons

- semcore/skeleton/CHANGELOG.md
- semcore/skeleton/src/Skeleton.jsx
- semcore/skeleton/src/style/skeleton.shadow.css
It was found that skeleton animation wasn't working, not sure how this happend in this overcomplecated component, but explicit passing animation duration in `SkeletonSVG` solves the issue. 
It started working as expected in my local playground. I am not sure we need any kind of video tests.
> [skeleton] fixed missing animation

- semcore/select/CHANGELOG.md
- semcore/select/__tests__/index.test.tsx
- semcore/select/src/Select.jsx
- website/docs/components/select/examples/options.tsx
> [select] disabled focus between Select.Option.Checkbox by Tab

- website/docs2/.vitepress/theme/style.css
> [website] small style fixes

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/DatePicker.jsx
- website/docs/style/design-tokens/components/design-tokens.json
https://github.com/semrush/intergalactic/issues/855
https://github.com/semrush/intergalactic/issues/856
I made Today button to take `disabled` prop into account and became disabled when today is not available to be selected.
Only manual testing.
> [date-picker] today button disabling wasn't working

- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
https://github.com/semrush/intergalactic/issues/858
Only manual testing.
> [popper] prevented popper from opening when Trigger is disabled.

- website/docs/components/breadcrumbs/breadcrumbs-a11y.md
- website/docs/components/button/button-a11y.md
- website/docs/components/color-picker/color-picker-a11y.md
- website/docs/components/dropdown-menu/dropdown-menu-a11y.md
- website/docs/components/dropdown/dropdown-a11y.md
- website/docs/components/pills/pills-a11y.md
- website/docs/components/select/select-a11y.md
- website/docs/components/switch/switch-a11y.md
- website/docs/components/tab-line/tab-line-a11y.md
- website/docs/components/tab-panel/tab-panel-a11y.md
- website/docs/components/time-picker/time-picker-a11y.md
- website/docs2/components/accordion/accordion-a11y.md
- website/docs2/components/breadcrumbs/breadcrumbs-a11y.md
- website/docs2/components/button/button-a11y.md
- website/docs2/components/pills/pills-a11y.md
- website/docs2/components/tab-line/tab-line-a11y.md
- website/docs2/components/tab-panel/tab-panel-a11y.md
> [website] small fixes for a11y documentation

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/component/ChartLegend/LegendItem/LegendItem.tsx
- website/docs/style/design-tokens/components/design-tokens.json
> [d3-chart] fixed imports path

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/style/data-table.shadow.css
#891 
I have tested it manually
> [data-table] removed animation from sort icon

- website/docs2/.vitepress/theme/style.css
- website/docs2/data-display/chart-legend/chart-legend.md
#871 
I have tested it manually
> [website] Fix/website style

- semcore/utils/CHANGELOG.md
- semcore/utils/src/findComponent.ts
Need this util method for #909 
i've tested it in #909
> [utils] added findAllComponents method

- semcore/breadcrumbs/CHANGELOG.md
- semcore/breadcrumbs/src/Breadcrumbs.jsx
- semcore/breadcrumbs/src/translations/de.json
- semcore/breadcrumbs/src/translations/en.json
- semcore/breadcrumbs/src/translations/es.json
- semcore/breadcrumbs/src/translations/fr.json
- semcore/breadcrumbs/src/translations/it.json
- semcore/breadcrumbs/src/translations/ja.json
- semcore/breadcrumbs/src/translations/ko.json
- semcore/breadcrumbs/src/translations/nl.json
- semcore/breadcrumbs/src/translations/pl.json
- semcore/breadcrumbs/src/translations/pt.json
- semcore/breadcrumbs/src/translations/sv.json
- semcore/breadcrumbs/src/translations/tr.json
- semcore/breadcrumbs/src/translations/vi.json
- semcore/breadcrumbs/src/translations/zh.json
> [breadcrumbs] fixed aria-current

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/types/Hover.d.ts
> [d3-chart] fixed types for children render function in tooltips

- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/Tooltip.jsx
> [tooltip] fixed working aria* in uncontrolled mode

- website/docs2/components/feature-popover/feature-popover.md
> [website] fixed example of featurePopover

- semcore/carousel/CHANGELOG.md
- semcore/carousel/src/index.ts
> [carousel] added reexport for types

- semcore/carousel/package.json
- semcore/carousel/src/Carousel.types.ts
> [carousel] fixed reexport for types

- website/docs2/layout/breakpoints/breakpoints-api.md
- website/docs2/layout/breakpoints/breakpoints-changelog.md
- website/docs2/layout/breakpoints/breakpoints-code.md
- website/docs2/layout/breakpoints/breakpoints.md
- website/docs2/style/design-tokens/design-tokens-changelog.md
- website/docs2/style/design-tokens/design-tokens-code.md
- website/docs2/style/design-tokens/design-tokens-usage-development.md
- website/docs2/style/design-tokens/design-tokens-usage.md
- website/docs2/style/design-tokens/design-tokens.md
> [website] add changelog page for Breakpoints and Design tokens

- tools/babel-plugin-styles/CHANGELOG.md
- tools/builder/mjs-imports-babelrc.js
By default build with `--modules=cjs` skipped `css` files.
> [global] fixed build for utils module with UI components and styles

- semcore/utils/CHANGELOG.md
> [global] fixed build utils

- semcore/checkbox/CHANGELOG.md
- semcore/checkbox/__tests__/index.test.tsx
- semcore/checkbox/src/Checkbox.jsx
removed aria-checked from input and set indeterminate from js
I've added unit tests and checked it manually
> [checkbox] fixed a11y

- website/docs/get-started-guide/dis-starter-guide/dis-starter-guide.md
Fixed typos and remove unnecessary information.
> [website] small fixes for design get started documentation

- semcore/core/CHANGELOG.md
- semcore/core/src/Component.tsx
- semcore/input-mask/CHANGELOG.md
- semcore/input-mask/__tests__/index.test.tsx
- semcore/input-mask/src/InputMask.tsx
- semcore/utils/CHANGELOG.md
- semcore/utils/src/inputProps.ts
> [input-mask, core, utils] fixed keypress `Backspace` in masked input

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/components/DateRangeComparatorAbstract.jsx
- semcore/date-picker/src/components/PickerAbstract.jsx
- semcore/date-picker/src/components/RangePickerAbstract.jsx
> [date-picker] Set displayedPeriod from current value for each open of Calendar

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/components/DateRangeComparatorAbstract.jsx
- semcore/date-picker/src/components/RangePickerAbstract.jsx
- semcore/date-picker/src/index.d.ts
Resolves https://github.com/semrush/intergalactic/issues/699.
It adds needed control to solve points 1 and 3. 
Point 2 have no sense since we replaced button trigger with input trigger and point 4 awaits design tokens update.
I also tried to resolve ref passing warning several times but failed. 
This feature also make internal code of date picker a way simpler.
All existing tests passed. All new apis works with well-tested handlers mechanism. Just to ensure I tested it manually and everything works as expected.
> [date-picker] added more apis to control over date-picker

- tools/continuous-delivery/src/collectPackages.ts
> [continuous-delivery] don't process changelog from intergalactic

- semcore/pills/CHANGELOG.md
- semcore/pills/src/style/pills.shadow.css
> [pills] fixed tabs behavior

- website/docs/components/progress-bar/progress-bar.md
For now, we don't display ProgressBar in playground.
> [website] fixed playground for progressBar

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/__tests__/index.test.tsx
- semcore/date-picker/src/DatePicker.jsx
- semcore/date-picker/src/DateRangePicker.jsx
- semcore/date-picker/src/MonthPicker.jsx
- semcore/date-picker/src/MonthRangePicker.jsx
- semcore/date-picker/src/components/PickerAbstract.jsx
- semcore/date-picker/src/components/RangePickerAbstract.jsx
- semcore/date-picker/src/index.d.ts
Fixes #995 
I have added unit tests and tested it manually
> [date-picker] date range keyboard

- .github/workflows/publish-unlocked-release.yml
> [global] publish new release before commit from old system

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/ScatterPlot.jsx
Fixed error in console for undefined values in ScatterPlot chart.
> [d3-chart] fixed error in ScatterPlot with undefined values

- tools/entry-point/CHANGELOG.md
- tools/entry-point/package.json
> [global] updated entrypoint

- tools/continuous-delivery/src/intg-release/publishRelease.ts
We need to get correct commit after all semrush-ci-whale commits for release
> [global] new release system 

- website/docs/core-principles/motion-principles-guide/motion-principles-guide.md
No dev review needed, just a small documentation update.
> [website] update Motion documentation

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/style/data-table.shadow.css
- website/docs/style/design-tokens/design-tokens.json
I've fixed styles of sort icon in data-table - if column has a `justifyContent=right`, we'll render sort icon `with position=absolute`
> [data-table] changed styles and animation of sort icon

- semcore/radio/CHANGELOG.md
- semcore/radio/__tests__/index.test.jsx
- semcore/radio/src/Radio.jsx
- semcore/radio/src/style/radio.shadow.css
For now, `disabled` prop doesn't work in component because of order in assignProps (and undefined value from context)
I've tested it manually and added unit-test
> [86bx484a1][radio] fixed disabled behaviour

- website/docs/index.md
No dev review needed, just removing festive mood from the main page.
> [website] remove festive mood

- pnpm-lock.yaml
- semcore/ui/CHANGELOG.md
- semcore/ui/components.json
- semcore/ui/package.json
- tools/entry-point/components.json
I've just added MiniCharts to ui package
> [86bx623vg][ui] added mini-charts

- semcore/checkbox/CHANGELOG.md
- semcore/checkbox/src/style/checkbox.shadow.css
- semcore/errors/CHANGELOG.md
- semcore/errors/src/style/errors.shadow.css
- semcore/inline-input/CHANGELOG.md
- semcore/inline-input/src/style/inline-input.shadow.css
- semcore/modal/CHANGELOG.md
- semcore/modal/src/style/modal.shadow.css
- semcore/radio/CHANGELOG.md
- semcore/radio/src/style/radio.shadow.css
We have a problem with style ordering. So, I've added more specific css selector to fix incorrect view in apps with out Checkbox component.
> [86bx69mvz][checkbox] added more specific css selector for Text component

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Bubble.jsx
If the amount of data has changed, there will be an error with exceeding the array boundaries. 
Additionally, the bubble will not be rendered if the duration is set to 0.
I have added a link to the example.
https://codesandbox.io/p/sandbox/naughty-allen-vx97dm
**Out of boundaries**
**duration=0**
> [d3-chart] fixed out of bounds data and animation at duration 0

- website/docs/components/tooltip/examples/info_icon.tsx
- website/docs/components/tooltip/tooltip-code.md
- website/docs/patterns/informer/informer-code.md
I've added example for `Icon` as a trigger for `Tooltip`.
> [86bx66bbw][website] added examples for tooltip

- semcore/drag-and-drop/CHANGELOG.md
- semcore/drag-and-drop/src/DragAndDrop.tsx
- semcore/drag-and-drop/src/index.d.ts
- semcore/drag-and-drop/src/translations/de.json
- semcore/drag-and-drop/src/translations/en.json
- semcore/drag-and-drop/src/translations/es.json
- semcore/drag-and-drop/src/translations/fr.json
- semcore/drag-and-drop/src/translations/it.json
- semcore/drag-and-drop/src/translations/ja.json
- semcore/drag-and-drop/src/translations/ko.json
- semcore/drag-and-drop/src/translations/nl.json
- semcore/drag-and-drop/src/translations/pl.json
- semcore/drag-and-drop/src/translations/pt.json
- semcore/drag-and-drop/src/translations/sv.json
- semcore/drag-and-drop/src/translations/tr.json
- semcore/drag-and-drop/src/translations/vi.json
- semcore/drag-and-drop/src/translations/zh.json
I've changed messages in d-n-d: added name for items in d-n-d if they have group.
I've tested it only manually
> [86bx355rt][drag-and-drop] Fixed a11y

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/__tests__/index.test.jsx
- semcore/feedback-form/src/FeedbackForm.jsx
I've added correct logic for `validationOnBlur=true` behaviour on our side, because of this comment - https://github.com/final-form/react-final-form/issues/293#issuecomment-413459508
I've tested it manually and added unit-tests
> [86bx6uev2][feedback-form] Fixed validation behaviour

- website/docs/style/typography/typography-code.md
> [website] added example for use Hint as Button

- website/docs/.vitepress/sidebarConfig.ts
- website/docs/.vitepress/theme/VPSidebarItem.vue
- website/docs/.vitepress/vite.config.ts
In this PR I have customized VP sidebar. The default sidebar is reused and extended a bit:
1. New `activeMatch` available. It allowed to removed 3rd level items and keep 2nd level items highlighted when nested page is opened.
2. Now items uncollapsing triggers other branches to collapse.
Manual testing is enough.
> [86bxa7vh6][website] custom sidebar with less nested items and branches auto collapse

- website/src/docs-components/DesignTokens.jsx
- website/src/docs-components/design-tokens.module.css
Had feedback about design tokens table is unusable in case of rebuilding specific components theme. That PR should fix it.
I just checked out that new table filter works good both on desktop and mobile devices.
> [website] added components fitler to design tokens table

- semcore/icon/CHANGELOG.md
> [icon] fix changelog

- website/docs/data-display/d3-chart/d3-chart-code.md
> Fix export example link in d3-chart-code

- website/docs/.vitepress/theme/DevportalLogo.vue
- website/docs/.vitepress/theme/Page404.vue
- website/docs/.vitepress/theme/VPSidebarItem.vue
- website/docs/.vitepress/theme/amplitude/amplitude.ts
- website/src/docs-components/PlaygroundGeneration.jsx
It is technical task - I've added some new events and added/changed params in current
> [86bx9xr04][website] fixed events for amplitude

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/__tests__/index.test.tsx
- semcore/d3-chart/src/a11y/focus.ts
- website/docs/style/design-tokens/design-tokens.json
`heavyFindNextFocusableElement` was made with a lot of excess logic and in a quite strange way. I much simplified it and ensured that it works in tested and in previously non-working cases.
Manually & with unit tests.
> [86bxdetnp][d3-chart] fixed that a11y module "Skip to content after plot" link was not working in some cases

- semcore/base-trigger/CHANGELOG.md
- semcore/base-trigger/src/FilterTrigger.jsx
I've removed check on activeElement in `handleClear` in `FocusTrigger`, because it works incorrect in some `focusLock` environments, and looks like in simple usage it is not needed too.
I've tested it manually because it is too difficult to write unit test for that.
> [86bxkw2b1][base-trigger] fixed returning focus on trigger

- semcore/typography/src/index.d.ts
- website/docs/style/typography/examples/list-with-custom-content.tsx
- website/docs/style/typography/typography-api.md
- website/docs/style/typography/typography-code.md
I've just added List.Item.Content types to docs
> [typography, website] added List.Item.Content to api docs

- semcore/base-trigger/CHANGELOG.md
- semcore/base-trigger/__tests__/index.test.tsx
- semcore/base-trigger/src/BaseTrigger.jsx
- semcore/base-trigger/src/ButtonTrigger.jsx
- semcore/select/__tests__/index.test.tsx
I've tested it manually and added unit test
> [86bxnx6we][base-trigger] added button tag for ButtonTrigger instead of div

- semcore/checkbox/CHANGELOG.md
- semcore/checkbox/__tests__/index.test.tsx
- semcore/checkbox/src/Checkbox.jsx
I've tested it manually and added unit test.
> [86bxp8ngf][checkbox] fixed double reading aria-label in checkbox without label

- website/docs/table-group/data-table/examples/customizing-header.tsx
I've changed the example how to use Tooltips in DataTable.Column for correct work from keyboard too.
> [86bxdtpkk][website] fixed example with tooltips on DataTable.Column

- semcore/scroll-area/CHANGELOG.md
- semcore/scroll-area/src/ScrollArea.jsx
- tools/testing-utils/setupTests.ts
> [86bxp0fxm][scroll-area] added scroll to the focused element in scroll area

- semcore/data-table/CHANGELOG.md
- semcore/data-table/__tests__/index.test.tsx
- semcore/data-table/src/Head.tsx
I've tested it manually and added unit test
> [86bxtrk91][data-table] Hide blue border on hidden DataTable.Head

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/DateRangePicker.jsx
- semcore/date-picker/src/MonthRangePicker.jsx
- semcore/date-picker/src/components/RangePickerAbstract.jsx
This PR enhances date range picker UX:
1. When user types date in range input trigger, it's immediately represented in calendar.
2. When user selects a date in calendar 
I tried to cover it with unit tests but failed 🫠
> [date-picker] range picker UX improvements

- semcore/d3-chart/src/component/Chart/BubbleChart.tsx
- semcore/d3-chart/src/index.js
- semcore/d3-chart/src/types/index.d.ts
- semcore/d3-chart/src/utils.ts
I've just move method to calculate domains to utils
> [d3-chart] refactoring calculate bubble domains method

- semcore/carousel/CHANGELOG.md
- semcore/carousel/src/Carousel.tsx
- semcore/carousel/src/Carousel.types.ts
- semcore/carousel/src/style/carousel.shadow.css
- website/docs/components/carousel/carousel-code.md
- website/docs/components/carousel/examples/carousel_with_indicators_only.tsx
- website/docs/style/design-tokens/design-tokens.json
We've added `keyboardFocusable` enhancer to all Carousel container and added `tabIndex=-1` to Buttons inside Carousel.
> [86bxv66aj][carousel] made all carousel container focusable

- .github/workflows/publish-prerelease.yml
- tools/continuous-delivery/bin/upload-static.ts
- tools/continuous-delivery/index.ts
- tools/continuous-delivery/package.json
- tools/continuous-delivery/src/utils/npmUtils.ts
> [chore] upload static logic

- semcore/pagination/CHANGELOG.md
- semcore/pagination/__tests__/index.test.tsx
- semcore/pagination/src/Pagination.jsx
We've had incorrect value of `currentPage` in onBlur handler, because we've got it before timeout. I've put it in timeout function.
Manually + added test
> [86bxxkp41][pagination] fixed values in input after keyboard navigation

- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/Tooltip.jsx
It was epic fail that I've added aria-live to trigger instead of popper. Fixing it.
For now we have no tests for it. Later I will add it.
> [86bxz2jg7][tooltip] removed aria-live from trigger and added it to popper

- semcore/notice-bubble/CHANGELOG.md
- semcore/notice-bubble/src/NoticeBubble.jsx
- semcore/notice-bubble/src/style/notice-bubble.shadow.css
My fault, I didn't correctly changed close button tag in https://github.com/semrush/intergalactic/pull/1204
This PR fixes it.
That time I've manually ensured that tag chagned.
> [86bxtpffy] Notice buble close button

- website/docs/components/inline-edit/examples/pseudo_network_interaction.tsx
- website/docs/components/inline-edit/inline-edit-code.md
- website/docs/style/design-tokens/design-tokens.json
No dev review needed. Small documentation fix.
> [website] fixed InlineEdit examples

- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/Tooltip.jsx
> [tooltip] fixed error about zIndex in DOM

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/style/tooltip.shadow.css
- website/docs/style/design-tokens/design-tokens.json
We [had DotCircle size used inside Tooltip](https://github.com/semrush/intergalactic/pull/967/commits/7680f7140ba22d3c757225e51cbd9d5f9f65e036#diff-e03a631f41907abd7e6977f69cbe776cde7812ac26f41c99bdea28c1d84f1a2a) diverging from design.
Tested locally using examples from our documentation.
> [86bxzrn20] Fix/d3 chart tooltip dot size

- semcore/utils/CHANGELOG.md
- semcore/utils/src/focus-lock/setFocus.ts
- semcore/utils/src/use/useFocusLock.ts
I've changed a condition to move focus to the last element in locked container - for now we check that current active node is follow previous active node and current active node is a descendant of the previous node.
> [86bxtqayu][utils] fixed condition to check on which element to move focus to in a locked container

- semcore/notice/CHANGELOG.md
- semcore/notice/src/Notice.jsx
- semcore/notice/src/translations/de.json
- semcore/notice/src/translations/en.json
- semcore/notice/src/translations/es.json
- semcore/notice/src/translations/fr.json
- semcore/notice/src/translations/it.json
- semcore/notice/src/translations/ja.json
- semcore/notice/src/translations/ko.json
- semcore/notice/src/translations/nl.json
- semcore/notice/src/translations/pl.json
- semcore/notice/src/translations/pt.json
- semcore/notice/src/translations/sv.json
- semcore/notice/src/translations/tr.json
- semcore/notice/src/translations/vi.json
- semcore/notice/src/translations/zh.json
`region` role better matches our notice component.
-
> [86bxtpffy][notice] role was changed from status to region

- semcore/popper/CHANGELOG.md
- semcore/popper/src/Popper.jsx
Fixed double open for selects in `<label>`
Manually
> [86by5t73d][portal] fixed propagation events from portal

- semcore/textarea/CHANGELOG.md
- semcore/textarea/src/Textarea.jsx
Added styles from original textarea to copying item.
Manually
> [86by4kcmj][textarea] added styles to clonned node from parent

- website/docs/components/drag-and-drop/drag-and-drop-a11y.md
- website/docs/components/drag-and-drop/drag-and-drop-api.md
Just added correct type for DnD.DropZone
> [website] fixed docs about dnd types

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/a11y/DataAccessibilityTable.tsx
- semcore/d3-chart/src/a11y/PlotA11yView.tsx
- semcore/d3-chart/src/a11y/hints.ts
- semcore/d3-chart/src/a11y/serialize.ts
- semcore/d3-chart/src/types/Plot.d.ts
- website/docs/data-display/d3-chart/d3-chart-code.md
- website/docs/data-display/d3-chart/examples/a11y-formatting.tsx
This PR enhances usages of a11y module by received feedback. See added example to see what api was added.
Manually by added example.
> [86bxyrm4u][d3-chart] a11y module values and titles formatting

- semcore/select/CHANGELOG.md
- semcore/select/src/Select.jsx
Fixes https://github.com/semrush/intergalactic/issues/1277
Manually, it's enough.
> [86by97hp4][select] fixed that `Select.InputSearch.Value` was undefined

- website/docs/.vitepress/theme/style.css
- website/docs/data-display/donut-chart/donut-chart.md
- website/docs/data-display/donut-chart/examples/legend-and-pattern-fill.tsx
- website/docs/data-display/scatterplot-chart/scatterplot-chart.md
- website/docs/data-display/venn-chart/venn-chart.md
I've just fixed examples for some charts
> [86by3xb9b][website] fixed props for render legend in some charts

- website/docs/.vitepress/theme/style.css
- website/docs/components/link/examples/link_addon.tsx
- website/docs/components/link/examples/link_inside_the_content.tsx
> [86bxbthmp][website] some fixes in styles

- website/docs/patterns/feedback-yes-no/examples/feedbackyesno-example.tsx
I've added active props for buttons in feedbackform example.
Manually
> [86by9quu4][website] fixed feedback example

- website/docs/data-display/area-chart/area-chart-api.md
- website/docs/data-display/bar-chart/bar-chart-api.md
- website/docs/data-display/bar-horizontal/bar-horizontal-api.md
- website/docs/data-display/bubble-chart/bubble-chart-api.md
- website/docs/data-display/bubble-chart/bubble-chart-d3-code.md
- website/docs/data-display/chart-legend/chart-legend-api.md
- website/docs/data-display/cigarette-chart/cigarette-chart-api.md
- website/docs/data-display/cigarette-chart/cigarette-chart-d3-code.md
- website/docs/data-display/cigarette-chart/examples/layouts.tsx
- website/docs/data-display/cigarette-chart/examples/tooltip-type.tsx
- website/docs/data-display/d3-chart/d3-chart-code.md
- website/docs/data-display/donut-chart/donut-chart-api.md
- website/docs/data-display/histogram-chart/histogram-chart-api.md
- website/docs/data-display/line-chart/line-chart-api.md
- website/docs/data-display/radar-chart/radar-chart-api.md
- website/docs/data-display/radial-tree-chart/radial-tree-chart-api.md
- website/docs/data-display/scatterplot-chart/scatterplot-chart-api.md
- website/docs/data-display/scatterplot-chart/scatterplot-chart-d3-code.md
- website/docs/data-display/stacked-area-chart/stacked-area-chart-api.md
- website/docs/data-display/stacked-bar-chart/stacked-bar-chart-api.md
- website/docs/data-display/stacked-horizontal-bar/stacked-horizontal-bar-api.md
- website/docs/data-display/venn-chart/venn-chart-api.md
- Updated documentation for chart's API pages.
- Updated a little bit examples for Cigarette chart and added descriptions.
Locally with our website.
> [website] update charts documentation

- website/docs/.vitepress/theme/style.css
Decided to update overlay color for zoomed images a little bit, so it will not look like you've left the page when the image is zoomed.
Locally.
Before:
After:
> [website] small style update

- semcore/accordion/CHANGELOG.md
- semcore/accordion/src/Accordion.jsx
This PR fixes that Pressing `Space` on focused `Accordion.Item.Toggle` was causing the page to scroll.
Manually, I'm sure that's enough for this type of bug.
> [86bybrz56][accordion] page scroll

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Head.tsx
- semcore/table/CHANGELOG.md
- semcore/table/src/StickyHead.jsx
Contains packaged:
1. https://github.com/semrush/intergalactic/pull/1310
2. https://github.com/semrush/intergalactic/pull/1311
> [data-table, table] packed prs from bbutkov

- website/docs/components/skeleton/skeleton-a11y.md
Accessibility recommendations for the Skeleton were unclear, and 2 of 3 were redundant. Removed reduntant ones and rephrased the one that's left.
> [website] Fix skeleton a11y recommendations

- semcore/textarea/CHANGELOG.md
- semcore/textarea/src/Textarea.jsx
Fixed calculation of min/max rows for clonnet textarea
Manually
> [86bygh3ha][textarea] fixed minRows prop

- semcore/ui/generate-reexport.ts
> [chore] fixed regexp for check default exports

- semcore/tab-line/CHANGELOG.md
- semcore/tab-line/src/TabLine.jsx
- semcore/tab-panel/CHANGELOG.md
- semcore/tab-panel/src/TabPanel.jsx
- website/docs/components/tab-line/examples/automatic_tab_activation.tsx
- website/docs/components/tab-panel/examples/manual_tab_activation.tsx
Just removed unnecessary `aria-pointset` attribute from tab items.
Manually with VO
> [86by4t71q][tab-line, tab-panel] removed unnecessary aria-pointset attribute

- semcore/input-number/CHANGELOG.md
- semcore/input-number/src/InputNumber.jsx
Fixed input number for work in controlled mode
Manually
> [86byp6922][input-number] fixed controlled mode

- website/docs/components/link/link-a11y.md
1. Moved `role=link` and `tabindex=0` to the attributes that the component already has.
2. Changed `span` to `a`.
3. Added a paragraph about contrast.
Manually.
> [86by8dtwg][website] Fixed link a11y docs

- website/docs/components/auto-suggest/examples/autosuggest_example.tsx
Just fixed a little example with auto suggest - removed onChange on Select which could disable list of options (if we keypress `Enter` without selected item)
Manually
> [86byp5zh0][website] fixed a little autosuggest example

- semcore/skeleton/package.json
- semcore/ui/CHANGELOG.md
- semcore/ui/package.json
- tools/entry-point/CHANGELOG.md
- tools/entry-point/components.json
- tools/entry-point/package.json
> Merge release tag into master

- website/docs/components/tag/tag-a11y.md
Fixed typo in the documentation.
> [website] fix typo in Tag documentation

- website/docs/patterns/feedback-rating/feedback-rating.md
Small fix to FeedbackRating documentation.
> [website] Update FeedbackRating

- website/docs/patterns/feedback-rating/feedback-rating-a11y.md
Small fix to FeedbackRating accessibility documentation.
> [website] Update a11y doc for FeedbackRating

- .gitignore
- .vale.ini
- semcore/breadcrumbs/CHANGELOG.md
- semcore/breadcrumbs/src/Breadcrumbs.jsx
- semcore/breadcrumbs/src/style/breadcrumbs.shadow.css
- website/docs/.vitepress/theme/style.css
- website/docs/components/breadcrumbs/examples/redefining_a_tag.tsx
- website/docs/components/breadcrumbs/examples/usage_example.tsx
Improve a11y for breadcrumbs
Manually
> [86by8d89p][breadcrumbs] some a11y improvements

- .gitignore
- .vale.ini
- semcore/fullscreen-modal/CHANGELOG.md
- semcore/fullscreen-modal/src/FullscreenModal.jsx
- website/docs/components/fullscreen-modal/fullscreen-modal-a11y.md
1. Added a recommendation to follow the overall heading hierarchy inside the modal.
2. Optimized a11y attributes tables structure.
3. Mentioned Close button's default aria-label.
4. Mentioned that Sections are implemented using html <section> (not implemented yet).
5. Mentioned that an aria-label should be defined for Section to work as a landmark.
Manually.
> [86bydf8cr][docs] Updated FullscreenModal a11y guide

- semcore/scroll-area/CHANGELOG.md
- semcore/scroll-area/src/ScrollArea.jsx
- semcore/scroll-area/src/style/scroll-area.shadow.css
Added check for resizing parent element for scroll area with hMax (wMax)
Manually
https://github.com/semrush/intergalactic/assets/8787452/67c09006-f1f4-414b-82a3-9918a8e53101
> [86byp524m][scroll-area] added auto resizing for ScrollArea if the parent element changes its size

- pnpm-lock.yaml
- semcore/stylelint-plugin/.npmignore
- semcore/stylelint-plugin/CHANGELOG.md
- semcore/stylelint-plugin/README.md
- semcore/stylelint-plugin/package.json
- semcore/stylelint-plugin/src/index.ts
- semcore/stylelint-plugin/tsconfig.json
- tools/entry-point/components.json
- website/docs/style/design-tokens/design-tokens.md
This PR introduces a stylelint plugin that validates design token names and throws errors if used design token library is not listed in the design token files of installed library.
On a clear project with stylelint.
> [86bygbgr1][stylelint-plugin] added stylelint plugin

- semcore/breadcrumbs/CHANGELOG.md
- semcore/breadcrumbs/src/style/breadcrumbs.shadow.css
Box-shadow on `overflow: hidden` elements are hidden. So, I've added hack with margins and paddings.
Manually
> [86bz9g8ev][breadcrumbs] fixed box-shadow displaying on focused item

- website/docs/.vitepress/theme/style.css
Noticed that h3 titles on API pages got their margins removed.
Locally.
> [website] fix for h3 styles on API pages

- .github/workflows/cd.yml
- .gitignore
- .vale.ini
- .vale/DevDocs/ArticlesHeadings.yml
- .vale/DevDocs/Contractions.yml
- .vale/DevDocs/DateFormat.yml
- .vale/DevDocs/ExtraSpace.yml
- .vale/DevDocs/Gender.yml
- .vale/DevDocs/HeadingLevel.yml
- .vale/DevDocs/Judgements.yml
- .vale/DevDocs/Latin.yml
- .vale/DevDocs/Master.yml
- .vale/DevDocs/MeaningfulLink.yml
- .vale/DevDocs/Names.yml
- .vale/DevDocs/NoEolWhitespace.yml
- .vale/DevDocs/Please.yml
- .vale/DevDocs/SentenceLength.yml
- .vale/DevDocs/Slave.yml
- .vale/DevDocs/USEnglish.yml
- .vale/DevDocs/WordList.yml
- package.json
This PR adds vale linter with some reviewed linting rules and ci/cd action.
In the first commit the branch contains linting errors. It preserved intentionally to see how it's handled.
–
> [86bz278ru][chore] added vale linter again

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/DataTable.tsx
I've added types for external users
> [data-table] fixed types for container ref

- semcore/carousel/CHANGELOG.md
- semcore/carousel/src/Carousel.tsx
- semcore/carousel/src/style/carousel.shadow.css
I've just moved hardcoded styles to .css file and set value from token
Manually
> [86bz9ygfm][carousel] changed border-radius to token instead of hardcoded value

- semcore/input-number/CHANGELOG.md
- semcore/input-number/__tests__/index.test.tsx
- semcore/input-number/src/InputNumber.jsx
We've changed logic in values formatter to fix values like `0.01`.
Also I've fixed values like `1.2.`
Manually + I've added a test
> [86bzf42gg][input-number] fixed hundredths fractions numbers

- website/docs/components/input-phone/examples/known_country_and_number_format.tsx
- website/docs/components/input-phone/examples/known_country_but_the_number_format_is_unknown.tsx
- website/docs/components/input-phone/examples/unknown_country_and_number_format.tsx
This PR fixes color of clear icons of input phone examples. Also it fixes show/hide behavior of one of examples.
Manually.
> [86bzfqyeb][docs] fixed input-phone clear icons color and behavior in examples

- semcore/input-number/CHANGELOG.md
- semcore/input-number/__tests__/index.test.tsx
- semcore/input-number/src/InputNumber.jsx
- semcore/notice-global/CHANGELOG.md
Fixed handle removing decimal part of number
Manually and I've added unit test
> [86bzhfp9j][input-number] fixed editing after removing decimal part

- website/docs/components/skeleton/examples/text_initial_loading.tsx
- website/docs/components/skeleton/skeleton-a11y.md
- website/docs/components/spin/examples/basic_example.tsx
- website/docs/components/spin/spin-a11y.md
- website/docs/components/spin/spin-api.md
- website/docs/components/spin/spin-code.md
- website/docs/components/spin/spin.md
An update of Spin and Skeleton A11y docs and examples that was accidentally missed earlier.
> [docs] Improved Spin and Skeleton a11y docs, added Spin example

- semcore/i18n-unplugin/CHANGELOG.md
- semcore/i18n-unplugin/README.md
- semcore/i18n-unplugin/src/index.ts
- website/docs/utils/i18n/i18n.md
This PR fixes support of intergalactic package with i18n-unplugin
It wasn't tested on real project. But I very belive that this changes is enough. After publishing I will test it on real-world project.
> [86bzjxmjt][i18n-unplugin] fixed working with intergalactic package

- website/docs/content/punctuation/punctuation.md
It's just a stub page for the writers to start working on their own section on our website.
The page will be available by this url: https://developer.semrush.com/intergalactic/content/punctuation/punctuation
> [docs] Added a stub page for the writers to edit

- website/docs/patterns/form/examples/inputtags-and-select.tsx
Our example with InputTags and Select was broken: it had weird paddings, errors was shown as `undefined` and it was impossible to add new tags. This small PR fixes it.
Manually on provided example.
> [86byt63ua][docs] fixed input-tags and select example functionality

- website/docs/content/punctuation/punctuation.md
Added styles for "DOs & DON'Ts" tables. 
Just as a local style for now, later we'll ask our devs to merge these styles into the global stylesheet.
It even works with the dark mode :)
> [docs] Added styled do-dont table

- website/docs/content/punctuation/punctuation.md
Just improved the semantics of the table (replaced header cells with TH), and updated the styles accordingly.
Nothing changed in the visuals.
> [website] Slightly improved DOs-DONTs table styles

- website/docs/data-display/chart-showcase/chart-showcase.md
Small fix to Charts showcase page. Updated the order of some links.
> [website] update Charts showcase page links

- website/docs/components/time-picker/examples/expanded_access_to_all_the_components.tsx
Small a11y fix in the TimePicker example: linked the visible label with the whole TimePicker instead of the Hours input.
> [docs] Fixed label in TimePicker example

- tools/continuous-delivery/src/intg-release/copyLibs.ts
I've fixed `intergalactic` package to work in `type=module` apps by added `package.json` to each component.
Manually
> [86bzkfjge][chore] added generator of package.json to each component in intergalactic package

- semcore/select/CHANGELOG.md
- semcore/select/src/Select.jsx
- semcore/select/src/style/input-search.shadow.css
> [86byteqkr][select] fixed input-search visual gap

- website/docs/.vitepress/config.ts
- website/docs/index.md
Currently we have "Intergalactic | Intergalactic" title on main page.
Manually.
> [86bzrk97g][website] fixed title

- pnpm-lock.yaml
- website/docs/.vitepress/theme/blog/BlogPostsMainPage.vue
- website/docs/.vitepress/theme/style.css
- website/package.json
To get latest a11y fixed by vitepress, we need to update it to latest version.
I have navigated over multiple pages and so far noticed only broken code snippets color. Lools like I've fixed it.
> [86bzqepz2][website] updated vitepress

- website/docs/components/inline-edit/examples/simple_use.tsx
- website/docs/components/modal/examples/changing_the_alignment.tsx
Some problems in hydration our examples in vitepress. We should use `window.TIMERs` because of that. 
Manually
> [86bzybu10][website] fixed error in console about aria-hidden in modal example

- semcore/input-number/CHANGELOG.md
- semcore/input-number/src/InputNumber.jsx
- website/docs/components/inline-edit/examples/simple_use.tsx
I've added possibility to add `onWheel` property with the default behaviour to the Input.Value component.
Manually
> [86bzx4e9t][input-number] added handler onWheel on Input.Value

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
Just fixed how to clear the role in dropdown menu popper.
Manually
> [86bzz17jr][dropdown-menu] fixed role in menu popper

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/src/FeedbackForm.jsx
I've fixed using theme property with `undefined` value in Notice component by added `use:`.
Manually
> [86bzz27tj][feedback-form] fixed notice theme prop

- website/docs/.vitepress/config.ts
- website/docs/.vitepress/theme/Tooltip.vue
- website/docs/.vitepress/theme/VPSocialLinks.vue
- website/docs/.vitepress/theme/VPSwitchAppearance.vue
- website/docs/.vitepress/vite.config.ts
This is just needed to meet formal a11y requirments.
Manually.
> [86bzrjwbq][website] added navbar theme toggler and social links hints (tooltips)

- semcore/pills/__tests__/pills.vo-test.ts
- website/docs/components/pills/examples/basic_example.tsx
Just a small PR with change that was forgotten to be added to https://github.com/semrush/intergalactic/pull/1579
> [docs] added missing label to pills radio example

- website/docs/.vitepress/theme/VPSidebarItem.vue
A11y audit consider using headings in sidebar to be wrong. So I've replaced it with just `p` tags.
Manually.
> [86bzwrk5v][website] removed headings from sidebar

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
- semcore/dropdown/CHANGELOG.md
- semcore/dropdown/src/Dropdown.jsx
- semcore/feature-popover/CHANGELOG.md
- semcore/select/__tests__/index.test.tsx
- semcore/tooltip/CHANGELOG.md
- semcore/tooltip/src/Tooltip.jsx
I've fixed focusing into popovers in dropdown and description.tooltip.
Manually
> [86bzzj6fx][dropdown, tooltip] fixed focusing in popovers

- semcore/feature-popover/CHANGELOG.md
- semcore/utils/src/themes/auto.css
- semcore/utils/src/themes/dark.css
- semcore/utils/src/themes/dark.json
- semcore/utils/src/themes/default.css
- semcore/utils/src/themes/default.json
- semcore/utils/src/themes/light.css
- semcore/utils/src/themes/light.json
- semcore/utils/theme/dark.json
- semcore/utils/theme/light.json
- website/docs/style/design-tokens/design-tokens.json
Changed z-index for modals (so they appear above tooltips).
Manually
> [86bzzfefk][chore] updated z-index for modals - set it more then for tooltips

- website/docs/.vitepress/code-theme.ts
- website/docs/.vitepress/renderSandbox.ts
- website/docs/.vitepress/theme/VPDoc.vue
- website/docs/.vitepress/theme/VPDocAside.vue
- website/docs/.vitepress/theme/VPDocFooter.vue
- website/docs/.vitepress/vite.config.ts
- website/src/docs-components/PlaygroundGeneration.jsx
In this PR I have ejected part of vitepress components to improve some little problems in it – like move main tag, add aria roles and so on.
Also, I've ejected code themes to allow our designers make it pop 
Manually.
> [86bzwrjfh][website] fixed landmark and ejected code theme source code

- website/docs/components/dropdown/dropdown-a11y.md
- website/docs/components/dropdown/dropdown-code.md
- website/docs/components/dropdown/dropdown.md
- website/docs/components/dropdown/examples/basic_usage.tsx
- website/docs/components/dropdown/examples/focus_interaction.tsx
Changes by pages:
1. A11y: updated keyboard interaction, added default ARIA properties and recommended properties.
2. Code: simplified some text. I thought it was repeating itself unnecessarily.
3. Examples (and also playground): changed trigger to a simple button to simplify all examples. Connected aria-labelledby with the trigger. Fixed paddings and text size.
4. Design: updated the list of suitable trigger components, keyboard interaction, fixed some wording.
> Update dropdown a11y docs and examples

- website/docs/.vitepress/theme/DevportalLogo.vue
- website/docs/.vitepress/theme/VPFeature.vue
- website/docs/.vitepress/theme/VPFeatures.vue
- website/docs/.vitepress/theme/VPHero.vue
- website/docs/.vitepress/theme/VPHome.vue
- website/docs/.vitepress/theme/blog/BlogPosts.vue
- website/docs/.vitepress/theme/blog/BlogPostsMainPage.vue
- website/docs/.vitepress/vite.config.ts
This PR contains simple fixes in out main page a11y. Actually I consider these changes not needed but they were noticed by a11y audit. To apply some changes to vitepress inner components, I've just ejected it and applied such changes.
Manually.
> [86bzwnrm5][website] fixed main page a11y issues

- website/docs/components/breadcrumbs/breadcrumbs-a11y.md
We didn't update documentation in the Accessibility documentation for Breadcrumbs, after the last accessibility fixes.
Manually.
> [docs] update Breadcrumbs A11y docs

- website/docs/.vitepress/theme/PageTopTabs.vue
- website/docs/.vitepress/theme/Sandbox.vue
- website/docs/.vitepress/theme/VPDoc.vue
- website/docs/.vitepress/theme/style.css
- website/src/docs-components/PlaygroundGeneration.jsx
Fixed that aside is inside of main on document page.
Fixed tabIndex placement on codeblocks.
> [website] fixed missed main landmark on documents page and fixed tabIndex of code blocks

- pnpm-lock.yaml
- website/docs/.vitepress/theme/VPNavBarSearchButton.vue
- website/docs/.vitepress/theme/VPSidebar.vue
- website/docs/.vitepress/vite.config.ts
- website/package.json
…
This enhanced webside a11y a bit.
Manually.
> [86bzwnnr5][website] added search lanmark and removed left sidebar as aside wrapper

- website/docs/table-group/data-table/data-table.md
- website/docs/table-group/data-table/examples/custom-footer-cells.tsx
- website/docs/table-group/table-showcase/table-showcase.md
Simple fix for roles in example
> [86c05hfc7][website] added roles for cells in custom-footercell example

- website/docs/components/accordion/accordion-code.md
- website/docs/components/accordion/examples/seo.tsx
Just added this example as we learned that people usually wants the accordion content to be indexed by search engines.
Manually.
> [86c09hyj4][accordion] added seo freidnly accordion example

- website/docs/table-group/data-table/examples/additional-elements-in-header.tsx
- website/docs/table-group/data-table/examples/download-status.tsx
I've fixed two examples in documentation for correct working in terms of accessibility
Manyallu
> [86c05hdeq][website] some accessibility fixes for tables with progressbar and loading

- website/docs/components/button/button.md
- website/docs/components/link/link.md
- Added posibility to see the ButtonLink component in the Button playground
- Added logic to show only relevant props depending on the chosen component
- In Link, fixed size labels (they had outdated font sizes in px)
- In both Link & ButtonLink, added logic to show Icon with size=L when font size > 300
Note: Disabled property doesn't work for ButtonLink, created a separate bug for that [86c0bd0km].
Manually.
> [86c0ag8xw] Update ButtonLink playground

- website/docs/table-group/data-table/examples/borders.tsx
- website/docs/table-group/data-table/examples/column-expand.tsx
I've removed unused sorting in two data-table examples
Manually
> [86c0d4neg][website] Fixed table docs examples

- website/docs/table-group/data-table/examples/sorting.tsx
I've fixed sorting in data-table example
Manually
> [86c0d4q8g][website] fixed sorting in data-table example

- website/docs/table-group/data-table/data-table-code.md
- website/docs/table-group/data-table/examples/pagination.tsx
I've added example with pagination to data-table
Manually
> [86c064k7w][website] added example with pagination to data-table

- website/docs/components/wizard/wizard-a11y.md
Added a description of Arrow-keys navigation to the Wizard A11y docs.
> [docs] Wizard.Stepper Arrows navigation

- website/docs/style/icon/examples/interactive.tsx
- website/docs/style/icon/icon-a11y.md
- website/docs/style/icon/icon-code.md
Updated interactive and non-interactive icon a11y attributes and recommendations. 
Added links and recommendations to use the native components (Button, ButtonLink, Link).
Added Hint to the example for the best in the world A11y :D
Manually.
> [docs] Updated Icon a11y guides

- semcore/utils/CHANGELOG.md
- semcore/utils/src/propsForElement.ts
I've added suppressHydrationWarning attribute support
Manually
> [86c0cnag7][utils] added suppressHydrationWarning attribute support

- website/docs/table-group/data-table/examples/access-to-cells.tsx
I've changed example with access to cells in data-table for work properly from keyboard.
Manually
> [website] fixed example with access to cells in data-table

- website/builder/typings/types.data.ts
> [86c089a1k][docs] added website api docs types mapping

- semcore/date-picker/CHANGELOG.md
- semcore/input-mask/CHANGELOG.md
- semcore/utils/CHANGELOG.md
- website/docs/.vitepress/theme/amplitude/amplitude-client.ts
- website/docs/.vitepress/theme/amplitude/amplitude.ts
Some improvements for statistic
> [86c0ewb2h][website] added pathname to init_app event and fixed left_menu-2 event

- website/docs/components/drag-and-drop/examples/with_primary_table.tsx
- website/docs/style/typography/examples/basic-usage.tsx
- website/docs/style/typography/examples/text-styles.tsx
- website/docs/style/typography/typography.md
There were several Hint-link references remaining in docs and examples. I replaced them with ButtonLink and default Link.
> [docs] Removed remaining hintlink references

- semcore/side-panel/CHANGELOG.md
- semcore/side-panel/src/SidePanel.jsx
Simple fix in side panel close button
Manually
> [side-panel] fixed using Button close with only icon

- semcore/d3-chart/src/types/Bar.d.ts
Added missing props to fix type error
> [d3-chart] added missing offset prop for Bar

- semcore/utils/CHANGELOG.md
- semcore/utils/theme/utils.ts
- website/docs/style/design-tokens/design-tokens.json
- website/docs/style/design-tokens/design-tokens.md
> [86bzgx59q][utils] display values for design tokens with modifications

- semcore/ellipsis/CHANGELOG.md
- semcore/ellipsis/src/Ellipsis.tsx
I've added `line-height` to calculation temporary element sizes.
Manually
> [86c0kba69][ellipsis] fixed incorrect calculation without line-height value

- semcore/d3-chart/src/Area.jsx
Reverts semrush/intergalactic#1690
> Revert "[d3-chart] pass strokeDasharray to Area when using pattern"

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Hover.jsx
- semcore/d3-chart/src/types/Hover.d.ts
Internal request to disable line in the chart by some condition.
Manually
https://github.com/user-attachments/assets/883eaa68-5f0a-4c6c-8b9b-a1e0f9710085
Here on the 2 value there is no line
> [d3-chart] added function type for hideHoverLine property in the Hover component

- website/docs/.vitepress/sidebarConfig.ts
Correct sidebar item wasn't selected for some sub-pages:
#
This PR fixes this issue for all pages we found.
I also removed the second level for one section that still had it.
> [86c0f5hfd][website] Fixed some sidebar items

- CONTRIBUTING.md
Updated contributing guide
Updated with steps to improve install process and running tests with more up to date information
> [chore] Update to contributing guide

- semcore/ellipsis/CHANGELOG.md
- semcore/ellipsis/src/Ellipsis.tsx
Change scrollWidth to width from boundaryRect in calculation size for text.
Manually
> [UIK-2529][ellipsis] fixed logic of showing tooltip with one line text and float width value

- semcore/utils/CHANGELOG.md
- semcore/utils/src/focus-lock/focusBorders.ts
I removed unnecessary promises in focus handlers for focusBorders.
Manyally
> [utils] removed unnecessary promise in focus handle for focusBorders

- website/docs/.vitepress/theme/amplitude/amplitude-client.ts
- website/docs/.vitepress/theme/amplitude/amplitude.ts
> [UIK-2235][website] Errors in ampl events

- website/docs/.vitepress/theme/amplitude/amplitude-client.ts
> [UIK-2166][website] moved referrer from user properties to init event properties

- website/docs/components/input-tags/examples/select_for_tag_filtering.tsx
- website/docs/components/input-tags/input-tags-code.md
Rewrote example for input tags with suggest list - from dropdown menu to select
Manually
> [UIK-2253][website] changed input tags example - using select instead of dropdown menu

- semcore/input-number/CHANGELOG.md
- semcore/input-number/__tests__/index.test.tsx
- semcore/input-number/src/InputNumber.jsx
I've added logic to resolve both `,` and `.` as decimal separators
Manually and I added a test
> [UIK-2177][input-number] added both . and , as decimal separator

- semcore/utils/CHANGELOG.md
- semcore/utils/src/ThemeProvider.tsx
I've added `display: contents` for ThemeProvider, because it should somehow depend to the layout. Also, I've fixed some types
Manually
> [UIK-2547][utils] changes in types and styles in ThemeProvider

- website/docs/.vitepress/theme/style.css
- website/docs/index.md
> [website] Revert "add Halloween mood 🎃 (#1716)"

- website/docs/data-display/donut-chart/examples/legend-and-pattern-fill.tsx
Added EmptyData to DonutPie with pattern and fill example 
manually
- [x Unit tests are not broken.
> [UIK-2542][docs] added EmptyData to DonutPie with pattern and fill example

- semcore/utils/CHANGELOG.md
- semcore/utils/src/ScreenReaderOnly.tsx
> [UIK-2524][utils] fixed position for ScreenReadOnly component

- website/docs/components/checkbox/examples/checkbox_with_other_components.tsx
Fixed checkbox and button link vertical alignment in documentation example
manually
> [UIK-2155][docs] fixed checkbox and button link vertical alignment

- semcore/utils/CHANGELOG.md
- semcore/utils/src/use/useFocusLock.ts
It's very difficult to test it, so, we will test it on RC
> [UIK-2589][utils] fixed hooks order in focusLock hook

- website/docs/data-display/bar-horizontal-compact/bar-horizontal-compact-a11y.md
- website/docs/data-display/bar-horizontal-compact/bar-horizontal-compact-api.md
- website/docs/data-display/bar-horizontal-compact/bar-horizontal-compact-d3-code.md
- website/docs/data-display/bar-horizontal-compact/d3-chart-changelog.md
Compact horizontal bar chart
1. Fixed links from the changelog to other pages.
2. Removed duplicate "bar" from page titles.
> [UIK-2607][website] Fixed Compact horizontal bar chart page titles and links

- website/docs/data-display/bar-chart/d3-chart-changelog.md
Removed wrong tab from the Changelog page in Bar chart.
> [website] Fixed tabs in Bar chart changelog

- .storybook/main.ts
- .storybook/preview.tsx
- package.json
- pnpm-lock.yaml
- semcore/button/__stories/Button.stories.tsx
- semcore/select/__stories/Select-Test.stories.tsx
- tools/testing-utils/playwright.ts
> Feature/new storybook  addon interactions

- semcore/feature-popover/CHANGELOG.md
- semcore/feature-popover/src/FeaturePopover.jsx
> [UIK-2622][feature-popover] fixed aria-labeledby prop

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/translations/de.json
- semcore/date-picker/src/translations/en.json
- semcore/date-picker/src/translations/es.json
- semcore/date-picker/src/translations/fr.json
- semcore/date-picker/src/translations/it.json
- semcore/date-picker/src/translations/ja.json
- semcore/date-picker/src/translations/ko.json
- semcore/date-picker/src/translations/nl.json
- semcore/date-picker/src/translations/pl.json
- semcore/date-picker/src/translations/pt.json
- semcore/date-picker/src/translations/sv.json
- semcore/date-picker/src/translations/tr.json
- semcore/date-picker/src/translations/vi.json
- semcore/date-picker/src/translations/zh.json
- Changed aira-label text of listbox
- Added translations for aira-label text of listbox
manually
> [date-picker] Changed aira-label text of listbox

- website/docs/components/link/link-a11y.md
- website/docs/components/link/link-api.md
- website/docs/components/link/link.md
- Slightly clarified existing a11y guidelines
- Implemented some Vale suggestions
- Changed the link to the common a11y guide to lead to its initial page, because a) it was broken, and b) the content of the "Link" section doesn't have much additional info, so I thought pointing to the main page would be more useful
> [UIK-2202][docs] Updated Link a11y page, linted other pages

- .storybook/preview.tsx
- stories/components/product-head/__stories__/component/long-long-title.tsx
- stories/components/product-head/__stories__/index.stories.tsx
I added a story for one of the product title use cases
Manually
> [UIK-2551][product-head] added example for long-long title with edit button

- website/docs/style/icon/icon-group.jsx
- website/docs/style/illustration/illustration-group.jsx
> [UIK-2665][website] fixed icon and illustation pages after intergalactic clean up

- semcore/base-trigger/src/style/link-trigger.shadow.css
> [chore] fixed link-trigger:focus outline

- semcore/input-tags/CHANGELOG.md
- semcore/input-tags/src/InputTags.tsx
> [UIK-2662][input-tags] fixed VO for not editable tags

- stories/components/input-tags/docs/examples/select_for_tag_filtering.tsx
> [UIK-2663][website] added SR for nothing found message in input-tags with select

- semcore/data-table/CHANGELOG.md
- semcore/data-table/__tests__/data-table.browser-test.tsx
- semcore/data-table/src/DataTable.tsx
- website/docs/table-group/data-table/examples/pagination.tsx
Manually and I added browser test for keyboard access
> [UIK-2647][data-table] fixed keyboard access

- semcore/dropdown-menu/__tests__/index.test.tsx
- semcore/dropdown/CHANGELOG.md
- semcore/dropdown/src/AbstractDropdown.tsx
- semcore/dropdown/src/Dropdown.jsx
- stories/components/dropdown-menu/docs/examples/basic.tsx
- stories/components/dropdown-menu/docs/examples/dropdown-menu.tsx
- stories/components/dropdown-menu/docs/examples/item_actions.tsx
- stories/components/dropdown-menu/docs/examples/list_item_types.tsx
- stories/components/dropdown-menu/docs/examples/nested.tsx
- stories/components/dropdown-menu/docs/examples/the_second_method.tsx
- stories/components/dropdown-menu/tests/Dropdown-menu.stories.tsx
- stories/components/dropdown-menu/tests/examples/on-visible-2nd.tsx
- stories/components/dropdown-menu/tests/examples/on-visible.tsx
- stories/components/select/tests/Select.stories.tsx
- stories/components/select/tests/examples/on_visible.tsx
Manually and I added unit test
> [UIK-2666][dropdown-menu] fixed double call of onVisibleChange handler

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/src/components/DateRangeComparatorAbstract.jsx
- semcore/utils/CHANGELOG.md
I've added `preventDefault` because LinkTrigger is button for now.
Manually
> [UIK-2756][date-picker] fixed blinking when opening

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/DataTable.tsx
> [UIK-2760] fixed data table keyboard interaction

- .storybook/manager.tsx
- package.json
- pnpm-lock.yaml
- stories/components/button/advanced/index.stories.tsx
- stories/components/button/docs/index.stories.tsx
- stories/package.json
- stories/utils/components/InteractionToggle.tsx
- stories/utils/playWrapper.ts
> [UIK-2746][stories] added interaction(play) toggler

- semcore/mini-chart/CHANGELOG.md
- semcore/mini-chart/__tests__/mini-chart.browser-test.tsx
- semcore/mini-chart/src/component/score/Donut.tsx
- semcore/mini-chart/src/component/trend/Bar.tsx
- semcore/mini-chart/src/component/trend/Line.tsx
- semcore/utils/src/ariaProps.ts
- stories/components/mini-chart/docs/examples/base_color.tsx
- stories/components/mini-chart/docs/examples/basic_usage.tsx
- stories/components/mini-chart/tests/MiniChart.stories.tsx
- stories/components/mini-chart/tests/examples/score-donuts.tsx
- stories/components/mini-chart/tests/examples/score-lines.tsx
- stories/components/mini-chart/tests/examples/trend-bars.tsx
- stories/components/mini-chart/tests/examples/trend-lines.tsx
- website/docs/data-display/mini-chart/mini-chart-a11y.md
> [UIK-2747][mini-chart] added role=img to all svg charts

- website/docs/components/tab-line/examples/automatic_tab_activation.tsx
- website/docs/components/tab-line/examples/disabled_tab_line_item.tsx
- website/docs/components/tab-line/examples/manual_tab_activation.tsx
- website/docs/components/tab-line/examples/tab_line_item_addons.tsx
- website/docs/components/tab-panel/examples/automatic_tab_activation.tsx
- website/docs/components/tab-panel/examples/disabled_tab_panel_item.tsx
- website/docs/components/tab-panel/examples/manual_tab_activation.tsx
- website/docs/components/tab-panel/examples/tab_panel_item_addons.tsx
> [UIK-2781][website][VPAT] fixed tab-line and tab-panel examples for vpat checks

- stories/components/color-picker/docs/examples/custom_trigger.tsx
> [UIK-2799][website][VPAT] fixed ids in color picker example

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/src/component/feedback-item/FeedbackItem.tsx
> [UIK-2775][website][VPAT] fixed aria-errormessage for feedback item

- website/docs/components/counter/examples/counter_in_filters.tsx
> [UIK-2770][website][VPAT] fixed counter in FilterTrigger example

- website/docs/.vitepress/theme/Sandbox.vue
- website/src/docs-components/PlaygroundGeneration.jsx
> [UIK-2751][website] added some accessible labels to the playground

- semcore/accordion/CHANGELOG.md
- semcore/accordion/src/Accordion.jsx
- website/docs/components/scroll-area/examples/scrollbar_out_of_container.tsx
- website/docs/components/tab-line/examples/automatic_tab_activation.tsx
- website/docs/components/tab-line/examples/disabled_tab_line_item.tsx
- website/docs/components/tab-line/examples/manual_tab_activation.tsx
- website/docs/components/tab-line/examples/tab_line_item_addons.tsx
- website/docs/components/tab-panel/examples/automatic_tab_activation.tsx
- website/docs/components/tab-panel/examples/disabled_tab_panel_item.tsx
- website/docs/components/tab-panel/examples/manual_tab_activation.tsx
- website/docs/components/tab-panel/examples/tab_panel_item_addons.tsx
> [UIK-2773][VPAT] aria controls

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/component/ChartLegend/LegendItem/LegendItem.tsx
- semcore/d3-chart/src/component/ChartLegend/LegendItem/LegendItem.type.ts
> [UIK-2778][d3-chart][VPAT] added aria-labelledby for LegendItem checkboxes

- website/src/docs-components/BaseTokens.jsx
- website/src/docs-components/DesignTokens.jsx
> [UIK-2787][website][VPAT] fixed input with addons

- stories/patterns/ux-patterns/summary/docs/examples/summary-with-minitrend.tsx
Just a small fix for our Vertical layout with Mini chart example.
We need to remove link from [not available value](https://developer.semrush.com/intergalactic/patterns/summary/summary-code#vertical-layout-with-mini-chart). It should be a plain text.
Manually.
> [UIK-2807][website] change link to text in summary example

- semcore/input-tags/src/InputTags.tsx
- stories/components/input-tags/advanced/examples/tags_with_addons.tsx
> [UIK-2393][input-tags] fixed focusable for inputTags.Text.Content

- website/docs/components/inline-input/inline-input.md
- website/docs/components/input-mask/input-mask.md
- website/docs/components/input-tags/input-tags.md
- website/docs/components/notice/notice.md
- website/docs/components/select/select.md
- website/docs/components/side-panel/side-panel.md
- website/docs/components/wizard/wizard.md
- website/docs/data-display/bar-chart/bar-chart.md
- website/docs/data-display/bar-horizontal/bar-horizontal.md
- website/docs/data-display/d3-chart/d3-chart.md
- website/docs/data-display/venn-chart/venn-chart.md
- website/docs/filter-group/filter-category/filter-category.md
- website/docs/filter-group/filter-kd-positions-volume/filter-kd-positions-volume.md
- website/docs/patterns/summary/summary.md
- website/docs/table-group/data-table/data-table.md
- website/docs/table-group/table-states/table-states.md
This PR fixes Level Access issues form UIK-2901 task.
Manually.
> [UIK-2901][website] update table headings

- stories/patterns/ux-patterns/informer/docs/Informer.stories.tsx
- stories/patterns/ux-patterns/informer/docs/examples/basic-usage.tsx
- website/docs/patterns/informer/examples/basic-usage.tsx
- website/docs/patterns/informer/informer-code.md
I've noticed that the wrong setting is applied to align-items, which affects the alignment of the large title and the icon next to it. This is just a small fix for the Informer example and is outside the scope of our tasks.
Manually.
**Before:**
**After:**
> [website] fixed typo in Informer example

- website/docs/components/feature-popover/feature-popover.md
- website/docs/components/inline-input/inline-input.md
- website/docs/components/progress-bar/progress-bar.md
- website/docs/components/textarea/textarea.md
- website/src/docs-components/PlaygroundGeneration.jsx
> [UIK-2895][website] VPAT fixed playground and examples on design page

- semcore/input-tags/CHANGELOG.md
- semcore/input-tags/src/InputTags.tsx
> [UIK-2841][input-tags] fixed aria-describedby for editable tags

- website/docs/.vitepress/theme/VPFeature.vue
- website/docs/.vitepress/theme/style.css
> [UIK-2789][website] Move link inside article

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/Plot.jsx
- semcore/d3-chart/src/component/Chart/AbstractChart.tsx
- semcore/d3-chart/src/translations/en.json
- semcore/illustration/CHANGELOG.md
- semcore/illustration/transform.ts
- stories/components/data-table/docs/examples/export-in-image.tsx
> [UIK-2771][d3-chart,illustration] added aria-hidden for svgs

- website/docs/utils/i18n/examples/basic.tsx
> [UIK-2908][website] Added accessible name to nav

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/style/hover.shadow.css
- semcore/d3-chart/src/style/radar.shadow.css
> [UIK-2904][d3-chart] VPAT added outline none for hover rect and line

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/src/FeedbackForm.jsx
- semcore/feedback-form/src/style/feedback-form.shadow.css
- website/docs/components/feedback/examples/default_feedback_form.tsx
- website/docs/patterns/feedback-yes-no/examples/feedbackyesno-example.tsx
> [UIK-2870][website] VPAT return focus to the success message in feedback-form example after fake request

- semcore/skeleton/CHANGELOG.md
- semcore/skeleton/__tests__/skeleton.axe-test.tsx
- semcore/skeleton/src/Skeleton.jsx
> [UIK-2953][skeleton] VPAT added role img to the skeleton

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Head.tsx
> [UIK-2957][data-table] VPAT fixed aria-colindex

- semcore/inline-edit/__tests__/inline-edit.axe-test.tsx
- semcore/inline-edit/src/InlineEdit.tsx
- stories/components/inline-edit/docs/examples/editable_tag.tsx
> [UIK-2960][website] VPAT removed unnecessary role button on container for editable tag in inline-edit

- website/docs/components/tab-line/examples/disabled_tab_line_item.tsx
- website/docs/components/tab-line/tab-line-code.md
- website/docs/components/tab-panel/examples/disabled_tab_panel_item.tsx
- website/docs/components/tab-panel/tab-panel-code.md
> [website] changed hint to tooltip in disabled tapPanel(tabLine).Items

- website/docs/.vitepress/theme/Sandbox.vue
> [UIK-2856][website] VPAT changed order of buttons in sandbox

- semcore/breadcrumbs/CHANGELOG.md
- semcore/breadcrumbs/src/Breadcrumbs.jsx
> [UIK-2876][breadcrumbs] VPAT changed active element to span

- website/docs/.vitepress/markdown-it-config.ts
> [UIK-2913][website] VPAT added tables without tabindex

- website/docs/.vitepress/theme/Sandbox.vue
- website/src/docs-components/PlaygroundGeneration.jsx
> [UIK-2914][website] VPAT removed tabIndex for html code blocks

- semcore/carousel/CHANGELOG.md
- semcore/carousel/src/Carousel.tsx
- semcore/carousel/src/Carousel.types.ts
- semcore/carousel/src/style/carousel.shadow.css
- website/docs/components/carousel/examples/carousel_with_indicators_only.tsx
> [UIK-2995][carousel] added handler for zoom data by enter/space

- website/docs/components/tab-panel/tab-panel-a11y.md
- website/docs/components/tab-panel/tab-panel-api.md
- website/docs/style/typography/examples/list-with-custom-bullets.tsx
- website/docs/style/typography/examples/list-with-custom-content.tsx
* Rewrote the text about right mouse click
* Changed the list example, so that the item with the "unchecked icon" text has a gray bullet
* Changed "uncheck" to "unchecked" for clarity
* Some other small inclusivity fixes
> [UIK-2959][docs] Inclusive language, small fix in list example

- semcore/utils/CHANGELOG.md
- semcore/utils/src/propsForElement.ts
I added new prop `onAuxClick` to allowedAttributes for components.
Manually
> [UIK-3044][utils] apply onAuxClick to components

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/src/component/ChartLegend/LegendItem/LegendItem.tsx
- website/docs/data-display/d3-chart/d3-chart-code.md
- website/docs/data-display/d3-chart/examples/low-level-components-use.tsx
A11y improvement of d3-chart component
manually
> [UIK-2975][d3-chart, docs] Add accessible name to chart

- semcore/notice-bubble/CHANGELOG.md
- semcore/notice-bubble/__tests__/notice-bubble.browser-test.tsx
- semcore/notice-bubble/src/NoticeBubble.jsx
> [UIK-2211][notice-bubble] added close by esc

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/DataTable.tsx
> [UIK-2761][data-table] fixed keyboard navigation in table with virtual scroll

- website/docs/style/icon/styles.module.css
Fixing documentation, icons were throwing error about blocked focus on click
manually
> [UIK-2962][docs] fixed icon throwing blocked focus error

- stories/components/notice-bubble/docs/examples/special_events_notice.tsx
I change one example of notice
> [UIK-2717][website] fixed special notice example

- stories/components/tag/docs/examples/custom_tag_color.tsx
- stories/components/tag/docs/examples/tag_addon.tsx
Changed texts in Tag examples to be more unique and to reflect the icons in them.
> [UIK-2997][docs] Fixed texts in Tag examples

- semcore/notice-bubble/__tests__/notice-bubble.browser-test.tsx
> [notice-bubble] fixed snapshots for browser tests

- stories/components/dropdown-menu/advanced/DropdownMenu.advanced.stories.tsx
- stories/components/dropdown-menu/advanced/examples/left-placement.tsx
I just added one new story for the DropdownMenu with auto flip for nested menu.
Manually
> [dropdown-menu] added example for the left placement for nested menu

- stories/patterns/ux-patterns/feedback-rating/docs/examples/feedback_rating_form.tsx
- website/docs/components/notice/notice-a11y.md
- website/docs/patterns/feedback-rating/feedback-rating-a11y.md
- website/docs/patterns/feedback-rating/feedback-rating-code.md
- website/docs/patterns/feedback-rating/feedback-rating.md
Forgot to do it together with the main task, so doing it in a separate PR.
1. Updated the a11y attributes list.
2. Changed the email error text in the example. It was "set correct email"—I think it was incorrect? Changed it to the same that's in the main feedback form.
3. Linter fixes. Left out 3 suggestions intentionally, one refers to the UI copy, and others I just felt that it's not worth complying with. I think we're justified to use "above/below" when we're describing UI design.
> [docs] Updated FeedbackRating a11y docs

- crowdin.yml
Migrated crowdin to enterprise. MR includes only crowdin config.update
manually by pushing test translation keys
> [UIK-3039][chore] migrated crowdin to enterprise

- semcore/ellipsis/CHANGELOG.md
- semcore/ellipsis/src/Ellipsis.tsx
- semcore/ellipsis/src/style/ellipsis.shadow.css
- stories/components/base-trigger/advanced/BaseTrigger.advanced.stories.tsx
- stories/components/base-trigger/advanced/examples/LinkTriggerAndEllipsis.tsx
- stories/components/ellipsis/test/examples/text_cases.tsx
> [UIK-3176][ellipsis,stories] added pre for ellipsis parts for preserve spacing

- semcore/wizard/__tests__/wizard.browser-test.tsx
- stories/components/wizard/docs/__tests__/custom_stepper_test.test.tsx
> [wizard] updated tests

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/src/component/feedback-rating/FeedbackRating.tsx
- semcore/feedback-form/src/component/feedback-rating/FeedbackRating.type.ts
- stories/patterns/ux-patterns/feedback-rating/docs/examples/feedback_rating_form.tsx
- stories/patterns/ux-patterns/feedback-yes-no/examples/docs/feedback-yes-no-example.tsx
- website/docs/components/feedback/examples/default_feedback_form.tsx
- website/docs/components/feedback/feedback-form-a11y.md
- website/docs/components/feedback/feedback-form-code.md
- website/docs/components/feedback/feedback.md
- website/docs/patterns/feedback-rating/feedback-rating-a11y.md
- website/docs/patterns/feedback-yes-no/feedback-yes-no-a11y.md
Some fixes for autocomplete email in forms
Manyally
> [UIK-3127][feedback-form] email autocomplete

- semcore/input-number/CHANGELOG.md
- semcore/input-number/src/InputNumber.jsx
> [UIK-3126][input-number] dynamically changed inputmode by step value

- stories/components/spin-container/docs/SpinContainer.stories.tsx
- stories/components/spin-container/docs/examples/usage_in_content.tsx
- stories/components/spin-container/docs/examples/usage_in_dropdown_lists.tsx
- website/docs/components/spin-container/spin-container-code.md
> [UIK-3214][stories] set for spin-container

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/Body.tsx
- stories/components/data-table/advanced/DataTable.advanced.stories.tsx
- stories/components/data-table/advanced/examples/link_in_table.tsx
fixed handle table cell focus for keyboard interaction only
Manually
> [UIK-3186][data-table] fixed copy link from table

- .gitlab-ci.yml
> [UIK-3149] republish docs

- tools/testing-utils/playwright.ts
I added mock to prevent loading illustrations from static server and only use local illustrations
Manually
> [chore] added mocks for illustrations

- pnpm-lock.yaml
- semcore/notice/CHANGELOG.md
- semcore/notice/package.json
> [UIK-3262][notice] added semcore/typography to deps

- website/docs/style/icon/icon-group.jsx
- website/docs/style/icon/icons-view.jsx
- website/docs/style/icon/styles.module.css
> [website] fixed some styles for icons page

- README.md
Removed the "border: 0" style from README.md.
There's currently an unnecessary border under the image, and that style doesn't work because it gets removed by github on render.
I don't know how to fix this, so let's just remove the non-functional style and keep the border.
> Removed unnecessary style from Readme

- stories/components/drag-and-drop/docs/__tests__/with_dropdownmenu.test.tsx
- stories/components/dropdown-menu/docs/__tests__/nested.test.tsx
- stories/components/dropdown-menu/docs/__tests__/nested_with_focusable.test.tsx
- stories/patterns/ux-patterns/auto-suggest/docs/__tests__/autosuggest_example.test.tsx
- stories/patterns/ux-patterns/confirmation-modal-dialog/docs/__tests__/ConfirmationModalDialog.test.tsx
> [stories] fixed story tests after renaming triggers

- semcore/utils/CHANGELOG.md
- semcore/utils/package.json
- tools/icon-transform-svg/config.js
- tools/icon-transform-svg/index.js
> [utils] added exports in package.json

- website/docs/.vitepress/vite.config.ts
> [website] fixed viteConfig for use asserts in imports

- semcore/bulk-textarea/CHANGELOG.md
- semcore/bulk-textarea/src/components/InputField/inputField.shadow.css
> [bulk-textarea] addded white bg for both themes

- semcore/portal/__tests__/index.test.tsx
I have renamed the unit tests and added two more to cover the previously untested prop, onMount. 
@ilyabrower While reviewing, could you please take a look at the test 'Verify onMount callback'? I aimed to test this prop but am not entirely sure it is tested properly.
> [UIK-3033][portal] tests

- semcore/outside-click/__tests__/index.test.tsx
Added some unit tests for better coverage
> [UIK-3036][outside-click] tests

- semcore/typography/CHANGELOG.md
- stories/components/icon/tests/examples/icons_in_other_elements_example.tsx
- website/docs/style/design-tokens/design-tokens-changelog.md
- website/docs/style/design-tokens/design-tokens-usage-development.md
- website/src/docs-components/Color.jsx
> [website] fixed imports on some pages

- semcore/notice-bubble/CHANGELOG.md
- semcore/notice-bubble/src/index.d.ts
- website/docs/components/notice-bubble/notice-bubble-api.md
> [UIK-3371][notice-bubble, website] fixed types

- semcore/date-picker/CHANGELOG.md
- semcore/date-picker/__tests__/date-picker.axe-test.tsx
- semcore/date-picker/__tests__/date-picker.browser-test.tsx
- semcore/date-picker/__tests__/date-picker.vo-test.ts
- semcore/date-picker/src/index.d.ts
- stories/components/date-picker/docs/date-picker.stories.tsx
- stories/components/date-picker/docs/examples/custom_date_ranges.tsx
- stories/components/date-picker/docs/examples/custom_day.tsx
- stories/components/date-picker/docs/examples/custom_header.tsx
- stories/components/date-picker/docs/examples/date_range_comparator.tsx
- stories/components/date-picker/docs/examples/date_range_comparator_advanced_use.tsx
- stories/components/date-picker/docs/examples/datepicker.tsx
- stories/components/date-picker/docs/examples/disabled_dates.tsx
- stories/components/date-picker/docs/examples/month_range_comparator_advanced_use.tsx
- stories/components/date-picker/docs/examples/monthrangepicker.tsx
- stories/components/date-picker/docs/examples/trigger_and_popper.tsx
- stories/components/date-picker/docs/examples/week_picker.tsx
- website/docs/components/date-picker/date-code.md
> [UIK-3384][date-picker] added type to describe disabled dates

- semcore/utils/CHANGELOG.md
- semcore/utils/package.json
> [utils] added color and if to the exports

- semcore/icon/CHANGELOG.md
- tools/icon-transform-svg/index.js
> [icon] added exports to package.json

- semcore/icon/CHANGELOG.md
- tools/icon-transform-svg/index.js
> Esm fix icons

- stories/components/input-phone/docs/examples/known_country_and_number_format.tsx
- stories/components/input-phone/docs/examples/known_country_but_the_number_format_is_unknown.tsx
Added `role=img` to InputPhone examples (2nd and 3d), so that flag in input/select trigger is announced as full country name.
Also edited aria-labels in the 2nd example, so that SR reads when focusing the input:
"Phone number, United States, ..."
(Flags in the Select Menu aren't announced, this is by design.)
> [UIK-3330][docs] Added role img to Flags in input phone

- semcore/utils/package.json
> [utils] added exports for css-theme files

- website/docs/components/radio/radio-code.md
Fixed an outdated text in a Radio example.
> Small fix in Radio example description

- semcore/bulk-textarea/src/components/InputField/InputField.tsx
- semcore/bulk-textarea/src/components/InputField/InputField.types.ts
- stories/components/bulk-textarea/advanced/BulkTextareaAdvanced.stories.tsx
- stories/components/bulk-textarea/advanced/examples/empty-values-in-paste-row.tsx
I changed type for PasteProps.lineProcessing to `lineProcessing?: (line: string, lineIndex: number, totalLinesCount: number) => string;`
Fixed bug with empty line as a result of lineProcessing.
Manually
> [UIK-3487][bulk-textarea] fixed paste empty array

- semcore/feedback-form/CHANGELOG.md
- semcore/feedback-form/src/component/feedback-rating/FeedbackRating.tsx
- stories/patterns/ux-patterns/feedback-rating/docs/examples/feedback_rating_form.tsx
- stories/patterns/ux-patterns/feedback-rating/tests/FeedbackRating.stories.tsx
- stories/patterns/ux-patterns/feedback-rating/tests/__tests__/with-error.test.tsx
- stories/patterns/ux-patterns/feedback-rating/tests/examples/with-error-on-send.tsx
> [UIK-3440][feedback-form] changed email in error notice to a link

- semcore/ui/generate-reexport.ts
- semcore/ui/package.json
I added logic to generate exports for ui package json
> [UIK-3488][chore] generate exports to package json for ui package

- semcore/utils/CHANGELOG.md
- semcore/utils/package.json
To have the possibility to import `createUUID` util.
Through using the local version of the library
> [chore] add createUUID to the exports list

- semcore/data-table/__tests__/data-table-accordion.browser-test.tsx
- semcore/data-table/src/components/Body/Body.tsx
I fixed how to handle accordions in render cells props
Manually
> [data-table] fixed accordion with render cells

- semcore/pills/src/style/pills.shadow.css
stay item with outline border even if hovered
Manually
> [UIK-3636][pills] outline for hevered

- pnpm-lock.yaml
- website/docs/get-started-guide/dev-starter-guide/production-tips.md
> [UIK-3644][website] fixed examples with css extraction and isolation with esm

- stories/components/data-table/tests/examples/cells-tests/dd-select-in-cell.tsx
> [stories] fixed example with interactive elements in cell

- semcore/data-table/__tests__/data-table-cells.browser-test.tsx
- semcore/data-table/src/components/DataTable/DataTable.tsx
- stories/components/data-table/tests/examples/cells-tests/one-merged-cell.tsx
> [UIK-3591][data-table] navigate to megred row from header

- stories/components/data-table/tests/examples/cells-tests/mini-chart-inline-edit-in-cell.tsx
> [UIK-3630][data-table] inline edit example

- semcore/format-text/CHANGELOG.md
- semcore/format-text/package.json
- semcore/format-text/vite.config.ts
- semcore/utils/CHANGELOG.md
- semcore/utils/package.json
- tools/shadow-loader/CHANGELOG.md
- tools/shadow-loader/index.js
- tools/shadow-loader/package.json
> [chore] some fixes for styles extraction and esb-build for format-text

- semcore/data-table/src/components/Body/style.shadow.css
> [UIK-3666][data-table] accordion button outline

- semcore/carousel/src/Carousel.tsx
- semcore/carousel/src/style/carousel.shadow.css
> [UIK-3675][carousel] focus visible

- semcore/select/src/InputSearch.jsx
> [UIK-3682][select] fixed InputSearch props

- semcore/slider/src/Slider.jsx
- stories/components/slider/docs/examples/numeric_slider.tsx
> [UIK-3681][stories] numeric slider fix

- semcore/data-table/src/components/Body/Row.tsx
- semcore/data-table/src/components/Body/style.shadow.css
- semcore/data-table/src/components/Head/Head.tsx
- semcore/data-table/src/components/Head/style.shadow.css
Added pointer style cursor to cells with checkboxes.
> [data-table] pointer cursor for checkbox cells

- semcore/data-table/src/components/DataTable/DataTable.tsx
> [UIK-3687][data-table] fixed keyboard navigation with accordions

- website/docs/table-group/data-table/data-table-api.md
- website/docs/table-group/data-table/data-table-code.md
> [UIK-3697][website] added description to AccessToCells example

- stories/components/button/advanced/examples/Basic.tsx
- stories/components/button/advanced/examples/ButtonHint.tsx
- stories/components/button/advanced/examples/ButtonSizes.tsx
- stories/components/button/docs/examples/button_accessibility.tsx
- stories/components/button/docs/examples/button_link.tsx
- stories/components/button/docs/examples/button_with_icon.tsx
- stories/components/button/docs/examples/button_with_loading.tsx
- stories/components/counter/docs/Counter.stories.tsx
- stories/components/dropdown/docs/examples/basic_usage.tsx
- stories/components/dropdown/docs/examples/focus_interaction.tsx
- stories/components/flags/docs/flags.stories.tsx
- stories/components/mini-chart/docs/examples/basic_usage.tsx
- stories/components/scroll-area/advanced/examples/scrollbar_out_of_container.tsx
> [UIK-3438][chore] replaced intergalactic to semcore in imports

- stories/components/data-table/tests/examples/accordion-tests/accordion-with-horizontal-scroll.tsx
- stories/components/data-table/tests/examples/accordion-tests/table-in-table-with-sorting.tsx
- stories/components/data-table/tests/examples/cells-tests/interactive-elements-in-cells.tsx
- stories/components/data-table/tests/examples/cells-tests/one-merged-cell.tsx
> [UIK-3438][stories] some type fixes

- .storybook/preview.tsx
- stories/components/icon/tests/Icon.stories.tsx
- stories/components/icon/tests/__tests__/all-icons-test.test.tsx
- stories/components/icon/tests/examples/all-icons-generated.tsx
- stories/components/illustration/tests/__tests__/all-allustrations-test.test.tsx
- stories/components/illustration/tests/examples/all-illustration-generated.tsx
- stories/components/illustration/tests/illustration.stories.tsx
- vite.config.ts
> [UIK-3305][stories] added all icons and all illustrations stories

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/components/Head/Column.tsx
Calculate sortable column width on the initial rendering too.
Manually
> [UIK-3700][data-table] fixed sortable column width on the initial rendering

- website/builder/typings/serializer.ts
> [UIK-2618][website] fixed types parser

- semcore/d3-chart/CHANGELOG.md
- semcore/d3-chart/package.json
- semcore/format-text/CHANGELOG.md
- semcore/format-text/package.json
> Fix esm in v16

- semcore/data-table/CHANGELOG.md
- semcore/data-table/__tests__/data-table-accordion.browser-test.tsx
- semcore/data-table/src/components/DataTable/DataTable.tsx
> [UIK-3761][data-table] fixed animations

- stories/components/data-table/docs/examples/checkbox-in-table.tsx
- tools/continuous-delivery/src/utils/getChangedFiles.ts
> [UIK-3762][stories] fixed table checkbox example

- semcore/data-table/src/components/DataTable/DataTable.tsx
> [UIK-3765][data-table] fixed keyboard nav

- semcore/i18n-unplugin/CHANGELOG.md
- semcore/i18n-unplugin/src/index.ts
> [UIK-3668][i18n-unplugin] fixed how to parse locales files in esm build

- playwright.axe.config.ts
- semcore/input-tags/__tests__/input-tags.axe-test.tsx
> [UIK-3810][input-tags] added axe test

- playwright.axe.config.ts
- semcore/notice/__tests__/notice.axe-test.tsx
- stories/components/notice/docs/examples/basic_notice.tsx
> [UIK-3810][notice] added axe test

- playwright.axe.config.ts
- semcore/notice-bubble/__tests__/notice-bubble.axe-test.tsx
> [UIK-3810][notice-bubble] added axe test

- CONTRIBUTING.md
> [UIK-3811][chore] updated contributing guide

- semcore/tab-line/__tests__/tabline.axe-test.ts
> [UIK-3810][tab-line] added axe test

- semcore/counter/__tests__/counter.axe-test.ts
> [UIK-3810][counter] added axe test

- semcore/progress-bar/__tests__/progress-bar.axe-test.ts
> [UIK-3810][progress-bar] added axe test

- semcore/input-number/__tests__/input-number.axe-test.ts
- stories/components/input-number/docs/examples/basic_example.tsx
> [UIK-3810][input-number] added axe test

- semcore/time-picker/__tests__/time-picker.axe-test.ts
> [UIK-3810][time-picker] added axe test

- semcore/drag-and-drop/__tests__/drag-and-drop.axe-test.ts
> [UIK-3810][drag-and-drop] added axe test

- semcore/feature-popover/__tests__/feature-popover.axe-test.ts
> [UIK-3810][feature-popover] added axe test

- semcore/notice-global/__tests__/notice-global.axe-test.ts
- stories/components/notice-global/docs/examples/basic_usage.tsx
> [UIK-3810][notice-global] added axe test

- semcore/carousel/__tests__/carousel.axe-test.ts
> [UIK-3810][carousel] added axe test

- semcore/select/CHANGELOG.md
- semcore/select/__tests__/multiselect.browser-test.tsx
- semcore/select/src/Select.jsx
Manually + with new browser test
> [UIK-3821][select] fixed focus after selecting options on popover

- semcore/dropdown-menu/CHANGELOG.md
- semcore/dropdown-menu/src/DropdownMenu.jsx
> [UIK-3836][dropdown-menu] fixed keyboard navigation to nested when parent was hovered by mouse

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/components/DataTable/DataTable.types.ts
- stories/components/data-table/docs/examples/accordion-inside-table.tsx
- stories/components/data-table/docs/examples/borders.tsx
- stories/components/data-table/docs/examples/multi-level-header.tsx
- stories/components/data-table/docs/examples/virtual-scroll-in-table-different-height.tsx
- stories/components/data-table/docs/examples/virtual-scroll-in-table.tsx
Small fix in `defaultGridTemplateColumnWidth` type and added `name` to column groups.
Manually
> [UIK-3840][data-table] fixed types

- semcore/data-table/__tests__/data-table-header.browser-test.tsx
- semcore/data-table/src/components/Head/Column.tsx
- stories/components/data-table/tests/examples/header-tests/sorting-with-interactive.tsx
- stories/components/data-table/tests/examples/header-tests/table-with-1tf-and diff-elements.tsx
> [UIK-3857][stories] fixed click by interactive element in sortable column

- semcore/data-table/src/components/DataTable/DataTable.tsx
- semcore/data-table/src/components/Head/Group.tsx
- semcore/data-table/src/components/Head/Group.type.ts
- semcore/data-table/src/components/Head/Head.tsx
- semcore/data-table/src/components/Head/style.shadow.css
- stories/components/data-table/tests/examples/scroll-tests/milti-level-horizontal-scroll.tsx
> [UIK-3860][data-table] example with two fixed groups

- website/docs/style/icon/icons-view.jsx
- website/docs/style/illustration/illustrations-view.jsx
- website/src/docs-components/BaseTokens.jsx
- website/src/docs-components/DesignTokens.jsx
Decreased timeouts from 500ms to 400ms, to check if that would help gather fuller data (we might be missing some values).
> [website] Decreased timeouts for sending search events to Amplitude

- semcore/core/package.json
Fixed exports for `useScrollBarWidth` hook.
> [core] added exports for useScrollBarWidth

- stories/components/data-table/tests/examples/accordion-tests/accordion-with-inline-edit.tsx
- stories/components/data-table/tests/examples/accordion-tests/accordion-with-link.tsx
- stories/components/data-table/tests/examples/accordion-tests/accordion-with-render-cell.tsx
- stories/components/data-table/tests/examples/accordion-tests/accrodion-with-more-interactive.tsx
- stories/components/data-table/tests/examples/accordion-tests/accrodion-with-select.tsx
- stories/components/data-table/tests/examples/cells-tests/checkbox.tsx
- stories/components/data-table/tests/examples/header-tests/multi-level-header-sticky.tsx
- stories/components/data-table/tests/examples/header-tests/multi-level-header.tsx
- stories/components/data-table/tests/examples/header-tests/multi-level-sorting.tsx
- stories/components/data-table/tests/examples/header-tests/multi-level-with-interactive.tsx
- stories/components/data-table/tests/examples/scroll-tests/horizontal-scroll-fixed-group.tsx
- stories/components/data-table/tests/examples/scroll-tests/horizontal-scroll.tsx
- stories/components/data-table/tests/examples/scroll-tests/w-100.tsx
- stories/components/data-table/tests/examples/virtualization/accordion-inside-table.tsx
- stories/components/data-table/tests/examples/virtualization/horizontal-scroll-fixed-group.tsx
- stories/components/data-table/tests/examples/virtualization/horizontal-scroll.tsx
- stories/components/data-table/tests/examples/virtualization/multi-level-header.tsx
- stories/components/data-table/tests/examples/virtualization/multi-level-sorting.tsx
- stories/components/data-table/tests/examples/virtualization/multi-level-with-interactive.tsx
> [chore] fixed types in data-table stories

- semcore/core/package.json
> [core] added export for setFocus

- website/docs/patterns/feature-highlight/feature-highlight.md
It wasn't obvious that you can't omit the `--intergalactic` in the FH tokens, so I added a tip about it to examples where it's relevant.
> [docs] added a tip about required prefix in FH tokens

- semcore/inline-input/src/InlineInput.tsx
- semcore/inline-input/src/index.ts
- semcore/inline-input/src/index.type.ts
- stories/components/inline-input/docs/examples/basic_usage.tsx
- stories/components/inline-input/tests/examples/styles.tsx
> Fix release

- tools/testing-utils/playwright.ts
- tools/testing-utils/vitest.ts
> [chore] update allure mapping

- pnpm-lock.yaml
- semcore/feature-popover/package.json
- semcore/feature-popover/src/index.d.ts
- website/docs/components/feature-popover/feature-popover-api.md
> [feature-popover] changed types descriptions

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/components/Body/Body.types.ts
- stories/components/data-table/docs/examples/accordion-inside-table.tsx
> [UIK-4020][data-table] fixed types in cellRenderProps

- website/.gitignore
Added vitepress temp configs to gitignore
> [chore] added vitepress temp config to gitignore

- semcore/data-table/CHANGELOG.md
- semcore/data-table/src/components/DataTable/DataTable.tsx
- semcore/data-table/src/components/Head/Column.tsx
- semcore/data-table/src/components/Head/Column.types.ts
- semcore/data-table/src/components/Head/Head.tsx
- semcore/data-table/src/components/Head/Head.types.ts
- semcore/data-table/src/components/Head/style.shadow.css
- stories/components/data-table/advanced/data-table.advanced.stories.tsx
- stories/components/data-table/advanced/examples/big_table_with_sticky_header.tsx
Manually + I added new advanced story
> [UIK-3938][data-table] fixed sticky header with width prop

- semcore/ui/CHANGELOG.md
- website/docs/get-started-guide/dev-starter-guide/dev-starter-guide.md
> [UIK-3894][core] update docs after Major16

- playground/components/Code.tsx
- playground/styles/styles.module.css
> UI k 2459/playground update proposal

- semcore/icon/CHANGELOG.md
- semcore/icon/package.json
- semcore/icon/svg/icon/Note/l.svg
- semcore/icon/svg/icon/Note/m.svg
- stories/components/icon/tests/examples/icons_in_other_elements_example.tsx
- website/docs/style/icon/icons-list.js
We have a request for a new icon for representing some notes.
Manually with storybook.
> [UIK-4121][icon] add Note icon

- playground/styles/styles.module.css
We somehow lost one small margin 😁
Manually.
**Before:**
**After:**
> [UIK-4144][website] 🔥 HOTFIX 😁 add lost margin to playground

- playground/components/ControlPanel.tsx
- playground/styles/styles.module.css
1. Fixed a couple of styles for the playground on the small screens
2. Moved top margin for labels to the component
Manually.
Before:
- Controls panel has an extra border radius on the top right
- Code block has no border-radius on the bottom left
- Canvas block has an extra border on the right
After:
> [website] small styles updates for playground

- semcore/button/CHANGELOG.md
- semcore/button/src/component/AbstractButton/AbstractButton.type.ts
- semcore/button/src/component/ButtonLink/ButtonLink.type.ts
> [UIK-4155][button] fixed size defaults in types

- playground/components/Code.tsx
- playground/hooks/useFocusableScrollRef.ts
Focusable elements without roles fail accessibility checks and confuse screen readers
> [UIK-4149][website] playground - add missing roles for focusable elements

- playground/components/Controls/SelectControl.tsx
- playground/components/Playground.tsx
- playground/components/ThemeContext.tsx
- website/docs/.vitepress/theme/Playground.vue
> [UIK-4200][website] added border for white colors

- semcore/pills/src/index.d.ts
> [UIK-3972][pills] changed how to deprecate pills behavior in docs
